"use client";

/**
 * Typed audio facade for exercises and the boss.
 *
 * Replaces scattered `playSound("foo")` string literals across the
 * codebase with a single typed surface: `audio.correct()`,
 * `audio.wrong()`, etc. Sound names live here, not at call sites, so
 * a future audiosprite migration is a 1-file change.
 *
 * VOICE INTERJECTIONS (additive layer):
 * On every feedback trigger (correct / wrong / streak / unlock /
 * victory / lessonStart) the facade ALSO fires a randomly-chosen
 * voiced micro-cue from Will (the product narrator) - "Nice work!",
 * "Try again!" etc. - that plays ON TOP of the existing chime, with
 * a tiny stagger so the chime hits first. The interjections live in
 * /public/audio/voice/interjections/ and are generated by
 * scripts/elevenlabs-generate-interjections.mjs.
 *
 * Behaviour:
 *   - Additive, never replaces the existing SFX chime.
 *   - One interjection plays at a time (a new trigger cancels the
 *     in-flight one) so spammed clicks don't pile up voices.
 *   - Pseudo-random shuffle: the same line never plays twice in a
 *     row per trigger.
 *   - Localstorage preference key `algorithmx-voice-interjections-v1`
 *     can be set to "false" to disable the voiced layer entirely;
 *     chimes still play.
 *   - Manifest fetched once per session (module-level cache).
 *
 * Also debounces hover to ~120ms (matches GameButton's existing
 * behaviour) and centralises the "use softWrong for kid-friendly
 * exercises" rule so we don't keep regressing to the sharp buzzer.
 *
 * Volume is intentionally NOT comfort-mode aware here - that lives in
 * SoundManager's category scaling. This module is about events.
 */

import { useEffect, useMemo } from "react";
import { playSound, stopBGM, playBGM, SoundManager } from "@/app/lib/sounds";
import { playSoftWrong, playBossHit, playVictoryStinger, playDefeatStinger } from "@/app/lib/gameEngine/audio";

let lastHoverAt = 0;
const HOVER_DEBOUNCE_MS = 120;

/* ─────────────────── VOICE INTERJECTIONS ─────────────────── */

type InterjectionTrigger =
  | "correct"
  | "wrong"
  | "streak3"
  | "streak5"
  | "streak7"
  | "unlock"
  | "victory"
  | "lessonStart";

interface InterjectionEntry {
  key: string;
  text: string;
  file: string;
}
interface InterjectionManifest {
  generatedAt: string;
  triggers: Partial<Record<InterjectionTrigger, InterjectionEntry[]>>;
}

const INTERJECTIONS_MANIFEST_URL = "/audio/voice/interjections/manifest.json";
const INTERJECTIONS_PREF_KEY = "algorithmx-voice-interjections-v1";
// Chime fires first, voice lands a fraction after. Without the stagger
// the two transients overlap and the chime gets masked.
const INTERJECTION_STAGGER_MS = 140;
// Interjections are raw HTMLAudioElements too (not routed through Howler),
// so cap their volume rather than letting `new Audio()` default to 1.0.
const INTERJECTION_VOLUME = 0.75;

/**
 * Master kill-switch for the voiced interjection layer. Flip to
 * `true` to re-enable Will saying "Nice work!" / "Try again!" etc.
 * on top of the existing SFX chimes. Currently OFF - the SFX-only
 * cues are the chosen feedback. Mirrors BGM_DISABLED pattern in
 * sounds.ts so the toggle is obvious.
 *
 * Side effect of `false`: the per-user localStorage preference
 * (algorithmx-voice-interjections-v1) is ignored - the layer is
 * globally muted regardless.
 */
const VOICE_INTERJECTIONS_ENABLED = false;

// Module-level cache so the manifest fetches once per session, not per
// hook consumer. Null = not loaded yet; an object = loaded; an empty
// object with no triggers = manifest 404/parse failed (silent fallback
// to chime-only mode).
let interjectionManifest: InterjectionManifest | null = null;
let interjectionManifestPromise: Promise<InterjectionManifest | null> | null = null;
function loadInterjectionManifest(): Promise<InterjectionManifest | null> {
  if (typeof window === "undefined") return Promise.resolve(null);
  if (interjectionManifest) return Promise.resolve(interjectionManifest);
  if (interjectionManifestPromise) return interjectionManifestPromise;
  interjectionManifestPromise = (async () => {
    try {
      const r = await fetch(INTERJECTIONS_MANIFEST_URL, { cache: "no-cache" });
      if (!r.ok) return null;
      const m = (await r.json()) as InterjectionManifest;
      interjectionManifest = m;
      return m;
    } catch {
      return null;
    }
  })();
  return interjectionManifestPromise;
}

// One audio element at a time - new trigger cancels the in-flight one.
let currentInterjectionEl: HTMLAudioElement | null = null;
function stopCurrentInterjection() {
  if (currentInterjectionEl) {
    try {
      currentInterjectionEl.pause();
      currentInterjectionEl.src = "";
    } catch {
      /* noop */
    }
    currentInterjectionEl = null;
  }
}

// Anti-repeat memory - never play the same line twice in a row per
// trigger. Maps trigger -> last-played key.
const lastPlayedByTrigger: Partial<Record<InterjectionTrigger, string>> = {};

function pickNext(
  trigger: InterjectionTrigger,
  entries: InterjectionEntry[],
): InterjectionEntry | null {
  if (entries.length === 0) return null;
  if (entries.length === 1) return entries[0];
  const last = lastPlayedByTrigger[trigger];
  // Pick any entry except the one we played last. If only one line
  // exists for this trigger, we'll fall through to it anyway.
  const pool = entries.filter((e) => e.key !== last);
  const choice = pool[Math.floor(Math.random() * pool.length)] ?? entries[0];
  lastPlayedByTrigger[trigger] = choice.key;
  return choice;
}

function isInterjectionEnabled(): boolean {
  if (typeof window === "undefined") return false;
  try {
    const raw = window.localStorage.getItem(INTERJECTIONS_PREF_KEY);
    // Default ON: only "false" disables.
    return raw !== "false";
  } catch {
    return true;
  }
}

/**
 * Fire a voiced interjection for a trigger. Non-blocking, swallows
 * autoplay errors silently (the chime is the guaranteed feedback;
 * the voice is enhancement).
 */
function fireInterjection(trigger: InterjectionTrigger) {
  if (typeof window === "undefined") return;
  if (!VOICE_INTERJECTIONS_ENABLED) return; // global kill-switch
  if (!isInterjectionEnabled()) return;

  // Don't block on manifest load - if it's not cached yet on the
  // first trigger of the session we just skip. Subsequent triggers
  // hit the cached manifest.
  loadInterjectionManifest().then((manifest) => {
    if (!manifest) return;
    const entries = manifest.triggers[trigger];
    if (!entries || entries.length === 0) return;
    const choice = pickNext(trigger, entries);
    if (!choice) return;

    window.setTimeout(() => {
      stopCurrentInterjection();
      const el = new Audio(choice.file);
      el.preload = "auto";
      el.volume = INTERJECTION_VOLUME; // never the 1.0 default
      currentInterjectionEl = el;
      el.addEventListener(
        "ended",
        () => {
          if (currentInterjectionEl === el) currentInterjectionEl = null;
        },
        { once: true },
      );
      el.addEventListener(
        "error",
        () => {
          if (currentInterjectionEl === el) currentInterjectionEl = null;
        },
        { once: true },
      );
      el.play().catch(() => {
        // Autoplay rejection or any other play failure - swallow
        // silently. The chime already played, so the user still got
        // feedback.
        if (currentInterjectionEl === el) currentInterjectionEl = null;
      });
    }, INTERJECTION_STAGGER_MS);
  });
}

/* ─────────────────── SIGNATURE SFX (ElevenLabs sound-generation) ─────────────────── */

interface SignatureSfxEntry {
  id: string;
  key: string;
  file: string;
  prompt: string;
  durationSeconds?: number;
}
interface SignatureSfxManifest {
  generatedAt: string;
  entries: SignatureSfxEntry[];
}

const SIGNATURE_SFX_MANIFEST_URL = "/audio/sfx-signature/manifest.json";

// Signature cues are raw HTMLAudioElements (not routed through the Howler
// SoundManager), so a bare `new Audio()` plays at the browser default of
// 1.0 - FULL volume. That made the mission-start sting blast when the
// lesson began. Cap it to a controlled, impactful-but-not-loud level.
// Nudge to taste.
const SIGNATURE_SFX_VOLUME = 0.4;

// Module-level cache - one fetch per session.
let signatureSfxManifest: SignatureSfxManifest | null = null;
let signatureSfxManifestPromise: Promise<SignatureSfxManifest | null> | null = null;
function loadSignatureSfxManifest(): Promise<SignatureSfxManifest | null> {
  if (typeof window === "undefined") return Promise.resolve(null);
  if (signatureSfxManifest) return Promise.resolve(signatureSfxManifest);
  if (signatureSfxManifestPromise) return signatureSfxManifestPromise;
  signatureSfxManifestPromise = (async () => {
    try {
      const r = await fetch(SIGNATURE_SFX_MANIFEST_URL, { cache: "no-cache" });
      if (!r.ok) return null;
      const m = (await r.json()) as SignatureSfxManifest;
      signatureSfxManifest = m;
      return m;
    } catch {
      return null;
    }
  })();
  return signatureSfxManifestPromise;
}

// One signature SFX at a time so spammed triggers don't pile up.
let currentSignatureEl: HTMLAudioElement | null = null;
function stopCurrentSignature() {
  if (currentSignatureEl) {
    try {
      currentSignatureEl.pause();
      currentSignatureEl.src = "";
    } catch {
      /* noop */
    }
    currentSignatureEl = null;
  }
}

/**
 * Play a signature SFX by id (matches sfx-signature.ts SIGNATURE_SFX
 * entries). Non-blocking, swallows manifest-missing + autoplay errors
 * silently - signature cues are enhancement, never the only feedback.
 */
function playSignature(id: string) {
  if (typeof window === "undefined") return;
  void loadSignatureSfxManifest().then((manifest) => {
    if (!manifest) return;
    const entry = manifest.entries.find((e) => e.id === id);
    if (!entry) return;
    stopCurrentSignature();
    const el = new Audio(entry.file);
    el.preload = "auto";
    el.volume = SIGNATURE_SFX_VOLUME; // never the 1.0 default - see constant
    currentSignatureEl = el;
    el.addEventListener(
      "ended",
      () => {
        if (currentSignatureEl === el) currentSignatureEl = null;
      },
      { once: true },
    );
    el.addEventListener(
      "error",
      () => {
        if (currentSignatureEl === el) currentSignatureEl = null;
      },
      { once: true },
    );
    el.play().catch(() => {
      if (currentSignatureEl === el) currentSignatureEl = null;
    });
  });
}

/* ─────────────────── GAME AUDIO FACADE ─────────────────── */

export interface GameAudio {
  // UI
  hover: () => void;
  tap: () => void;
  transition: () => void;
  back: () => void;
  select: () => void;
  // Feedback (kid-friendly defaults)
  correct: () => void;
  wrong: () => void;                 // soft variant
  hardWrong: () => void;             // sharp variant (only for danger contexts)
  streak: (n: number) => void;
  hint: () => void;
  // Reward
  xpTick: () => void;
  unlock: () => void;
  badgeEarned: () => void;
  levelUp: () => void;
  starEarned: () => void;
  // Boss
  bossHit: () => void;
  bossRoar: () => void;
  bossDefeated: () => void;
  bossPhaseChange: () => void;
  victory: () => void;
  defeat: () => void;
  // BGM
  bgmLesson: () => void;
  bgmBattle: () => void;
  bgmVictory: () => void;
  stopBgm: () => void;
  // Lesson lifecycle (interjection-only - chime already covered by
  // existing transition/select/etc cues at the call site)
  lessonStart: () => void;
  // Signature SFX (ElevenLabs sound-generation). Plays a custom-
  // designed branded cue by id. See app/lib/sfx-signature.ts for the
  // catalogue of available ids.
  signature: (id: string) => void;
  // Tactile game-interaction cues (Howler registry, low-latency).
  cardFlip: () => void; // memory/match card flip
  drop: () => void; // placing/sorting a tile (stamp/thunk)
  heal: () => void; // repairing/fixing something (sparkle)
}

/**
 * Stable, memoised game-audio facade. Safe to consume from a hook deps
 * array (the returned object identity is stable across renders for
 * the lifetime of the component).
 */
export function useGameAudio(): GameAudio {
  // Load the SFX registry into Howler. SoundManager.play(key) is a silent
  // no-op until preloadSFX() has run - and DynamicLesson never preloaded,
  // so every game sound was inaudible. Idempotent (guarded internally).
  useEffect(() => {
    try {
      SoundManager.getInstance().preloadSFX();
    } catch {
      /* ignore */
    }
  }, []);

  return useMemo<GameAudio>(
    () => ({
      hover: () => {
        const now = performance.now();
        if (now - lastHoverAt < HOVER_DEBOUNCE_MS) return;
        lastHoverAt = now;
        playSound("hover");
      },
      tap: () => playSound("click"),
      transition: () => playSound("transition"),
      back: () => playSound("back"),
      select: () => playSound("select"),
      // Tactile game-interaction cues.
      cardFlip: () => playSound("cardFlip"),
      drop: () => playSound("drop"),
      heal: () => playSound("heal"),

      // Default `wrong` is the SOFT variant. Use `hardWrong` only when
      // the context legitimately calls for a sharper cue (e.g. boss
      // taking heavy damage). The previous default of `playSound("wrong")`
      // was too punishing for ages 6-9 learning exercises.
      correct: () => {
        playSound("correct");
        fireInterjection("correct");
      },
      wrong: () => {
        playSoftWrong();
        fireInterjection("wrong");
      },
      hardWrong: () => playSound("wrong"),
      streak: (n: number) => {
        if (n >= 7) {
          playSound("streak7");
          fireInterjection("streak7");
        } else if (n >= 5) {
          playSound("streak5");
          fireInterjection("streak5");
        } else if (n >= 3) {
          playSound("streak3");
          fireInterjection("streak3");
        }
      },
      hint: () => playSound("reveal"),

      xpTick: () => playSound("xpGain"),
      unlock: () => {
        playSound("lock");
        fireInterjection("unlock");
      },
      badgeEarned: () => playSound("badgeEarned"),
      levelUp: () => playSound("levelUp"),
      starEarned: () => playSound("starEarned"),

      bossHit: () => playBossHit(),
      bossRoar: () => playSound("bossRoar"),
      bossDefeated: () => playSound("bossDefeated"),
      bossPhaseChange: () => playSound("phaseChange"),
      // Victory triggers BOTH the stinger AND a "You did it!" /
      // "Cyber Hero!" interjection - the moment deserves the layered
      // payoff.
      victory: () => {
        playVictoryStinger();
        fireInterjection("victory");
      },
      defeat: () => playDefeatStinger(),

      bgmLesson: () => playBGM("bgmLesson"),
      bgmBattle: () => playBGM("bgmBattle"),
      bgmVictory: () => playBGM("bgmVictory"),
      stopBgm: () => stopBGM(),

      // Interjection-only trigger - no SFX chime alongside, because
      // the lesson-start moment already has a screen transition cue
      // wired separately.
      lessonStart: () => fireInterjection("lessonStart"),

      signature: (id: string) => playSignature(id),
    }),
    []
  );
}

/* ─────────────────── PREFERENCE HELPERS ─────────────────── */

/**
 * Read the current voice-interjections preference. Useful for any
 * settings UI you build (default: true).
 */
export function getVoiceInterjectionsEnabled(): boolean {
  return isInterjectionEnabled();
}

/**
 * Persist the voice-interjections preference. Pass `false` to disable
 * (chimes still play); `true` to re-enable. No-op outside the browser.
 */
export function setVoiceInterjectionsEnabled(enabled: boolean): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(INTERJECTIONS_PREF_KEY, String(enabled));
  } catch {
    /* noop */
  }
  if (!enabled) stopCurrentInterjection();
}
