import type { Track } from "./types";

/* The job-title picker on the invite landing: about a hundred titles
 * mapped to the nine desks. Anything unmapped is General. Searchable, so
 * a learner types "payroll" and lands on Finance without knowing the desk
 * names. Keep each desk's list in the order a learner should see it: the
 * most common titles first, because the landing shows the first few. */
export const JOB_TITLES: { title: string; track: Track }[] = [
  { title: "Accountant", track: "finance" },
  { title: "Finance manager", track: "finance" },
  { title: "Bookkeeper", track: "finance" },
  { title: "Payroll administrator", track: "finance" },
  { title: "Accounts assistant", track: "finance" },
  { title: "Accounts payable", track: "finance" },
  { title: "Accounts receivable", track: "finance" },
  { title: "Credit controller", track: "finance" },
  { title: "Finance director", track: "finance" },
  { title: "Financial controller", track: "finance" },
  { title: "Management accountant", track: "finance" },
  { title: "Finance assistant", track: "finance" },
  { title: "Payroll manager", track: "finance" },
  { title: "Purchase ledger clerk", track: "finance" },
  { title: "Auditor", track: "finance" },
  { title: "Tax adviser", track: "finance" },
  { title: "Treasury analyst", track: "finance" },
  { title: "Underwriter", track: "finance" },
  { title: "Claims handler", track: "finance" },

  { title: "Solicitor", track: "legal" },
  { title: "Paralegal", track: "legal" },
  { title: "Compliance officer", track: "legal" },
  { title: "Legal assistant", track: "legal" },
  { title: "Legal secretary", track: "legal" },
  { title: "Trainee solicitor", track: "legal" },
  { title: "Partner", track: "legal" },
  { title: "Data protection officer", track: "legal" },
  { title: "In-house counsel", track: "legal" },
  { title: "General counsel", track: "legal" },
  { title: "Company secretary", track: "legal" },
  { title: "Contracts manager", track: "legal" },
  { title: "Risk manager", track: "legal" },
  { title: "Conveyancer", track: "legal" },

  { title: "HR manager", track: "hr" },
  { title: "HR advisor", track: "hr" },
  { title: "HR administrator", track: "hr" },
  { title: "Recruiter", track: "hr" },
  { title: "HR business partner", track: "hr" },
  { title: "People partner", track: "hr" },
  { title: "Talent acquisition", track: "hr" },
  { title: "Learning and development", track: "hr" },
  { title: "Training manager", track: "hr" },
  { title: "Wellbeing lead", track: "hr" },

  { title: "Office manager", track: "ops" },
  { title: "Administrator", track: "ops" },
  { title: "Operations manager", track: "ops" },
  { title: "Project manager", track: "ops" },
  { title: "Executive assistant", track: "ops" },
  { title: "Personal assistant", track: "ops" },
  { title: "Team leader", track: "ops" },
  { title: "Facilities manager", track: "ops" },
  { title: "Procurement", track: "ops" },
  { title: "Programme manager", track: "ops" },
  { title: "Business analyst", track: "ops" },
  { title: "Consultant", track: "ops" },
  { title: "Supply chain", track: "ops" },
  { title: "Logistics coordinator", track: "ops" },
  { title: "Warehouse manager", track: "ops" },
  { title: "Health and safety officer", track: "ops" },
  { title: "Quality manager", track: "ops" },

  { title: "Sales executive", track: "sales" },
  { title: "Account manager", track: "sales" },
  { title: "Marketing manager", track: "sales" },
  { title: "Business development manager", track: "sales" },
  { title: "Sales manager", track: "sales" },
  { title: "Sales director", track: "sales" },
  { title: "Account executive", track: "sales" },
  { title: "Marketing executive", track: "sales" },
  { title: "Marketing assistant", track: "sales" },
  { title: "Content manager", track: "sales" },
  { title: "Social media manager", track: "sales" },
  { title: "Communications manager", track: "sales" },
  { title: "PR manager", track: "sales" },
  { title: "Bid manager", track: "sales" },
  { title: "Telesales", track: "sales" },

  { title: "Customer service advisor", track: "support" },
  { title: "Receptionist", track: "support" },
  { title: "Help desk", track: "support" },
  { title: "Client services", track: "support" },
  { title: "Customer success manager", track: "support" },
  { title: "Customer service manager", track: "support" },
  { title: "Support engineer", track: "support" },
  { title: "Call centre agent", track: "support" },
  { title: "Client relationship manager", track: "support" },
  { title: "Front of house", track: "support" },

  { title: "IT support", track: "it" },
  { title: "IT manager", track: "it" },
  { title: "Software developer", track: "it" },
  { title: "Software engineer", track: "it" },
  { title: "Systems administrator", track: "it" },
  { title: "Data analyst", track: "it" },
  { title: "DevOps engineer", track: "it" },
  { title: "Product manager", track: "it" },
  { title: "Network engineer", track: "it" },
  { title: "Cyber security analyst", track: "it" },
  { title: "Security analyst", track: "it" },
  { title: "Service desk analyst", track: "it" },
  { title: "Data engineer", track: "it" },
  { title: "Data scientist", track: "it" },
  { title: "Database administrator", track: "it" },
  { title: "Cloud engineer", track: "it" },
  { title: "Web developer", track: "it" },
  { title: "QA tester", track: "it" },
  { title: "Technical architect", track: "it" },
  { title: "IT director", track: "it" },
  { title: "Chief technology officer", track: "it" },

  { title: "Director", track: "leadership" },
  { title: "Managing director", track: "leadership" },
  { title: "Head of department", track: "leadership" },
  { title: "Chief executive", track: "leadership" },
  { title: "Chief operating officer", track: "leadership" },
  { title: "Chief financial officer", track: "leadership" },
  { title: "Managing partner", track: "leadership" },
  { title: "Founder", track: "leadership" },
  { title: "Owner", track: "leadership" },
  { title: "Board member", track: "leadership" },
  { title: "Non-executive director", track: "leadership" },

  { title: "Other", track: "general" },
  { title: "Apprentice", track: "general" },
  { title: "Intern", track: "general" },
  { title: "Graduate trainee", track: "general" },
  { title: "Contractor", track: "general" },
  { title: "Volunteer", track: "general" },
];

/* Words a learner might type that are in no title but should find the
 * desk: "IT" on its own, "tech", "money", "law". */
export const TRACK_KEYWORDS: Record<Track, string[]> = {
  finance: ["finance", "money", "invoice", "ledger", "accounts", "payroll", "tax", "audit", "insurance"],
  legal: ["legal", "law", "lawyer", "compliance", "gdpr", "privacy", "contract", "risk"],
  hr: ["hr", "people", "human resources", "recruitment", "hiring", "training"],
  ops: ["ops", "operations", "admin", "office", "project", "facilities", "logistics"],
  sales: ["sales", "marketing", "comms", "brand", "growth", "clients"],
  support: ["support", "customer", "service", "reception", "helpdesk", "call centre"],
  it: ["it", "tech", "technology", "engineering", "developer", "software", "data", "security", "cyber", "infrastructure", "cloud"],
  leadership: ["leadership", "executive", "board", "c-suite", "management", "ceo", "cfo", "coo", "director"],
  general: ["general", "other", "everyone", "anything else"],
};

/* The order desks appear in on the invite landing. */
export const TRACK_ORDER: Track[] = ["finance", "legal", "hr", "ops", "sales", "support", "it", "leadership", "general"];
