import type { Track } from "./types";

/* The job-title picker on the invite landing: about sixty titles mapped to
 * the eight tracks. Anything unmapped is General. Searchable, so a learner
 * types "payroll" and lands on Finance without knowing the track names. */
export const JOB_TITLES: { title: string; track: Track }[] = [
  { title: "Accountant", track: "finance" },
  { title: "Accounts assistant", track: "finance" },
  { title: "Accounts payable", track: "finance" },
  { title: "Accounts receivable", track: "finance" },
  { title: "Bookkeeper", track: "finance" },
  { title: "Credit controller", track: "finance" },
  { title: "Finance director", track: "finance" },
  { title: "Finance manager", track: "finance" },
  { title: "Financial controller", track: "finance" },
  { title: "Payroll administrator", track: "finance" },
  { title: "Payroll manager", track: "finance" },
  { title: "Purchase ledger clerk", track: "finance" },
  { title: "Compliance officer", track: "legal" },
  { title: "Data protection officer", track: "legal" },
  { title: "Legal assistant", track: "legal" },
  { title: "Legal secretary", track: "legal" },
  { title: "Paralegal", track: "legal" },
  { title: "Partner", track: "legal" },
  { title: "Solicitor", track: "legal" },
  { title: "Trainee solicitor", track: "legal" },
  { title: "HR administrator", track: "hr" },
  { title: "HR advisor", track: "hr" },
  { title: "HR business partner", track: "hr" },
  { title: "HR manager", track: "hr" },
  { title: "People partner", track: "hr" },
  { title: "Recruiter", track: "hr" },
  { title: "Talent acquisition", track: "hr" },
  { title: "Account executive", track: "sales" },
  { title: "Account manager", track: "sales" },
  { title: "Business development manager", track: "sales" },
  { title: "Content manager", track: "sales" },
  { title: "Marketing executive", track: "sales" },
  { title: "Marketing manager", track: "sales" },
  { title: "Sales director", track: "sales" },
  { title: "Sales executive", track: "sales" },
  { title: "Client services", track: "support" },
  { title: "Customer service advisor", track: "support" },
  { title: "Customer success manager", track: "support" },
  { title: "Help desk", track: "support" },
  { title: "Receptionist", track: "support" },
  { title: "Support engineer", track: "support" },
  { title: "Administrator", track: "ops" },
  { title: "Executive assistant", track: "ops" },
  { title: "Facilities manager", track: "ops" },
  { title: "Office manager", track: "ops" },
  { title: "Operations manager", track: "ops" },
  { title: "Personal assistant", track: "ops" },
  { title: "Procurement", track: "ops" },
  { title: "Project manager", track: "ops" },
  { title: "Data analyst", track: "it" },
  { title: "DevOps engineer", track: "it" },
  { title: "IT manager", track: "it" },
  { title: "IT support", track: "it" },
  { title: "Product manager", track: "it" },
  { title: "Software developer", track: "it" },
  { title: "Software engineer", track: "it" },
  { title: "Systems administrator", track: "it" },
  { title: "Chief executive", track: "leadership" },
  { title: "Chief operating officer", track: "leadership" },
  { title: "Director", track: "leadership" },
  { title: "Head of department", track: "leadership" },
  { title: "Managing director", track: "leadership" },
  { title: "Managing partner", track: "leadership" },
  { title: "Other", track: "general" },
];
