"use client";

/**
 * Narration block for reading-heavy info screens.
 *
 * Plays pre-recorded ElevenLabs MP3s when available (the realistic
 * path), falling back to the browser's Web Speech API only when the
 * manifest is missing the requested lines. The manifest lives at
 * /public/audio/voice/manifest.json and is generated by
 * scripts/elevenlabs-generate-narration.mjs.
 *
 * Audio files play sequentially (one per line) so the on-screen
 * active-line highlight stays in sync with what's being heard, and
 * each file was generated with previous_text/next_text context so
 * prosody flows naturally between lines.
 *
 * If the manifest is missing entries for ANY line in this block, the
 * whole block falls back to Web Speech to avoid a jarring mid-block
 * voice change. If no TTS is available either, the captions are the
 * fallback - the UI stays informative.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { useComfortMode } from "@/app/lib/comfortMode";
import { isAudioMuted, subscribeAudioMute } from "@/app/lib/audioMute";
import NarrationClickGuard from "@/app/components/lesson/NarrationClickGuard";
import { useLessonTheme } from "@/app/components/lesson/LessonThemeContext";

// The narration is played via a raw `new Audio()`, which defaults to 1.0
// (FULL volume) - that was the loud blast when a lesson screen opened, so
// it must always be set explicitly. The voice should be clear and dominant
// but comfortable; 0.50 keeps it clearly above the faint music bed (0.03)
// without hurting young ears.
const NARRATION_VOLUME = 0.5;

// Narration auto-plays when a Learn screen opens (back ON now that the
// voice/delivery is approved and the volume is capped + safe). Set to
// `false` for button-only.
const NARRATION_AUTOPLAY = true;

// The narration `lines` carry the SPOKEN script, which includes eleven_v3
// emotional tags like [warmly] / [excited] / [whispers] that direct the
// performed delivery. Those must never appear in the on-screen captions -
// strip anything in square brackets (and tidy spacing) for display only.
function stripTags(line: string): string {
  return line
    .replace(/\[[^\]]*\]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

export interface InfoNarrationProps {
  /** Short lines read in order. Keep each ≤ 12 words. */
  lines: string[];
  /**
   * Voice selection: which character's recorded voice to use. Also
   * drives the synth-voice pitch when falling back to browser TTS.
   * "narrator" = the storyteller voice (a different voice from Sarah).
   */
  speaker?: "adam" | "layla" | "narrator";
  /** Auto-play on mount. Defaults to true; user toggle overrides. */
  autoPlay?: boolean;
  /** Fires once when playback ends (or fails/blocks) — used to chain a
   *  follow-up line, e.g. the narrator finishes, then Sarah asks the question. */
  onDone?: () => void;
  /**
   * Accent colour (hex) for the box chrome — the ♪ ring, border, label and
   * "Read aloud" button. Lets a themed screen (e.g. a signature game with its
   * own palette) tint the narration block to match instead of the default
   * cyan, so it never clashes with the surrounding art. Omit for the classic
   * cyan look (byte-identical to before).
   */
  accent?: string;
  /**
   * Render the full-screen "Listening… tap to skip" click-guard while speaking.
   * Default true. Set false when the HOST already gates the screen (e.g. the
   * exercise intro has its own "Listen first…" countdown + a modal overlay that
   * sits ABOVE the guard) — otherwise two "listen" indicators stack and fight.
   */
  guard?: boolean;
  /**
   * When true, NEVER fall back to the robotic browser TTS voice: if this block
   * has no pre-recorded clip in the manifest, stay SILENT (captions mode) and
   * fire onDone immediately so any host gate releases. Use this for narration
   * that is only recorded for SOME weeks (e.g. the boss questions and the
   * wrong-answer panels, recorded for Week 15 but not yet the others) so an
   * un-recorded week is silent instead of robot-voiced. Default false (the
   * classic behaviour: recorded → TTS → captions).
   */
  recordedOnly?: boolean;
}

interface ManifestEntry {
  key: string;
  speaker: "adam" | "layla" | "narrator";
  voice: string;
  /** Full joined block text - the key used at lookup time. */
  text: string;
  /** Original line array for display reference. */
  lines: string[];
  file: string;
}
interface Manifest {
  generatedAt: string;
  model: string;
  chunkStrategy?: "line" | "block";
  entries: ManifestEntry[];
}

const MANIFEST_URL = "/audio/voice/manifest.json";

// Module-level singleton so we fetch the manifest once for the whole
// session, not on every InfoNarration mount. Fetch resolves to null
// if the manifest is missing (404 / network) - in that case we go
// straight to TTS.
let manifestCache: Manifest | null = null;
let manifestPromise: Promise<Manifest | null> | null = null;

// Only ONE narration plays at a time across the whole app. When any instance
// starts, it stops whichever OTHER instance is still sounding — this kills a
// previous screen's clip bleeding into the next one (and any accidental double
// of two mounted narrations). Holds the currently-playing instance's stop().
let activeNarrationStop: (() => void) | null = null;
async function loadManifest(): Promise<Manifest | null> {
  if (manifestCache) return manifestCache;
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    try {
      // `no-cache` (NOT no-store) so the browser still keeps a copy but
      // always revalidates with the server. Stops a stale, force-cached
      // manifest from pointing at MP3 files that were replaced when the
      // generator was re-run with new voice settings.
      const r = await fetch(MANIFEST_URL, { cache: "no-cache" });
      if (!r.ok) return null;
      const m = (await r.json()) as Manifest;
      manifestCache = m;
      return m;
    } catch {
      return null;
    }
  })();
  return manifestPromise;
}

/**
 * Build the lookup key for a block. Must match exactly how the
 * generator joins the lines (see scripts/elevenlabs-generate-
 * narration.mjs joinBlock()): a single space between lines,
 * collapsed whitespace, trimmed. Keep these two in sync.
 */
function buildBlockKey(lines: string[]): string {
  return lines
    .map((l) => l.trim())
    .filter(Boolean)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

function findBlockEntry(
  manifest: Manifest | null,
  speaker: "adam" | "layla" | "narrator",
  lines: string[],
): ManifestEntry | null {
  if (!manifest) return null;
  const key = buildBlockKey(lines);
  return (
    manifest.entries.find((e) => e.speaker === speaker && e.text === key) ??
    null
  );
}

export default function InfoNarration({
  lines,
  speaker = "adam",
  autoPlay = true,
  accent,
  onDone,
  guard = true,
  recordedOnly = false,
}: InfoNarrationProps) {
  // Themed accent (hex). An explicit `accent` prop wins; otherwise the week
  // theme's accent (so every narration box on a themed week is one colour);
  // otherwise the classic cyan (un-themed weeks stay byte-identical).
  // `${A}NN` appends an 8-digit-hex alpha channel.
  const themeAccent = useLessonTheme()?.accent;
  const A = accent ?? themeAccent ?? "#7df0ff";
  // Fire onDone exactly once (natural end, error, or blocked) so a caller can
  // chain a follow-up line without it double-firing.
  const onDoneRef = useRef(onDone);
  onDoneRef.current = onDone;
  const doneFiredRef = useRef(false);
  const fireDone = useCallback(() => {
    if (doneFiredRef.current) return;
    doneFiredRef.current = true;
    onDoneRef.current?.();
  }, []);
  const comfort = useComfortMode();
  const [speaking, setSpeaking] = useState<boolean>(false);
  // `armed` bridges the ~400ms pre-roll between autoplay committing and the
  // audio actually sounding (`speaking`). Without it the click-guard is down
  // for that window and a fast tap skips the very start of the voice. See the
  // autoplay effect + the disarm effect below.
  const [armed, setArmed] = useState<boolean>(false);
  const [activeLine, setActiveLine] = useState<number>(-1);
  // Resolved playback mode for this block. "loading" until the
  // manifest fetch completes; "recorded" if the block has an entry;
  // "tts" if no entry AND browser TTS is available; "captions" if
  // neither is usable (audio button hidden).
  const [mode, setMode] = useState<"loading" | "recorded" | "tts" | "captions">(
    "loading",
  );
  // Recorded-mode: the single block MP3 path. One file = whole block,
  // played as one continuous stream so there are no gaps between
  // sentences (v4-block-flow generator change).
  const [blockFile, setBlockFile] = useState<string | null>(null);
  // Refs for cleanup of in-flight playback.
  const audioElRef = useRef<HTMLAudioElement | null>(null);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);
  // Cancellation token so a re-speak() interrupts the prior sequence
  // without late audio events advancing it.
  const playRunRef = useRef<number>(0);

  const ttsSupported =
    typeof window !== "undefined" && "speechSynthesis" in window;

  // Resolve mode once the manifest loads.
  useEffect(() => {
    let cancelled = false;
    void loadManifest().then((manifest) => {
      if (cancelled) return;
      const entry = findBlockEntry(manifest, speaker, lines);
      if (entry) {
        setBlockFile(entry.file);
        setMode("recorded");
      } else if (ttsSupported && !recordedOnly) {
        setMode("tts");
      } else {
        // No recording — either TTS is unavailable, or the caller demanded
        // recordedOnly (never robot-voice). Either way: silent captions.
        setMode("captions");
      }
    });
    return () => {
      cancelled = true;
    };
  }, [lines, speaker, ttsSupported, recordedOnly]);

  // Nothing to play (captions = no recording and TTS suppressed/unavailable):
  // fire onDone once so a host gate waiting on the voice (e.g. the boss
  // unlocking its answer buttons) releases instead of hanging on audio that
  // will never sound. Recorded/TTS modes fire onDone from playback end instead.
  useEffect(() => {
    if (mode === "captions") fireDone();
  }, [mode, fireDone]);

  /* ────── Stop both pipelines cleanly ────── */
  // Per-instance stable handle to this instance's stop(), used for the global
  // single-narration registry (compared by identity).
  const stopRef = useRef<() => void>(() => {});
  const stop = useCallback(() => {
    playRunRef.current++; // invalidate any in-flight sequence
    // Recorded
    if (audioElRef.current) {
      try {
        audioElRef.current.pause();
        audioElRef.current.src = "";
      } catch {
        /* noop */
      }
      audioElRef.current = null;
    }
    // TTS
    if (ttsSupported) {
      try {
        window.speechSynthesis.cancel();
      } catch {
        /* noop */
      }
    }
    // Release the global single-narration slot if we held it.
    if (activeNarrationStop === stopRef.current) activeNarrationStop = null;
    setSpeaking(false);
    setActiveLine(-1);
  }, [ttsSupported]);
  stopRef.current = stop;

  /* ────── Recorded playback: one continuous block-level MP3 ────── */
  const playRecorded = useCallback(
    (file: string) => {
      stop();
      // Global single-narration: stop any OTHER instance still sounding, then
      // claim the slot (so a previous screen's clip can't overlap this one).
      if (activeNarrationStop && activeNarrationStop !== stopRef.current) activeNarrationStop();
      activeNarrationStop = stopRef.current;
      const runId = ++playRunRef.current;
      setSpeaking(true);
      // No per-line active highlight under recorded mode - the whole
      // block plays as one continuous audio, so highlighting a single
      // bullet at a time would lie about what's being heard. All
      // bullets stay at full opacity during playback.
      setActiveLine(-1);

      const el = new Audio(file);
      el.preload = "auto";
      el.volume = NARRATION_VOLUME; // never the raw 1.0 default - see constant
      audioElRef.current = el;
      el.addEventListener(
        "ended",
        () => {
          if (runId !== playRunRef.current) return;
          setSpeaking(false);
          audioElRef.current = null;
          fireDone();
        },
        { once: true },
      );
      el.addEventListener(
        "error",
        () => {
          if (runId !== playRunRef.current) return;
          setSpeaking(false);
          audioElRef.current = null;
          fireDone();
        },
        { once: true },
      );
      // Browsers may reject autoplay without a user gesture; we
      // swallow the rejection - the toggle button is the gesture
      // path so the next user tap will succeed.
      el.play().catch(() => {
        if (runId !== playRunRef.current) return;
        setSpeaking(false);
        audioElRef.current = null;
        fireDone();
      });
    },
    [stop],
  );

  /* ────── TTS fallback (one utterance per block) ────── */
  const playTts = useCallback(() => {
    if (!ttsSupported || lines.length === 0) return;
    stop();
    if (activeNarrationStop && activeNarrationStop !== stopRef.current) activeNarrationStop();
    activeNarrationStop = stopRef.current;
    const runId = ++playRunRef.current;
    const text = lines.join(". ");
    const utter = new SpeechSynthesisUtterance(text);
    utter.rate = comfort.enabled ? 0.9 : 1.0;
    utter.pitch = speaker === "layla" ? 1.15 : speaker === "narrator" ? 0.85 : 0.95;
    utter.volume = 1;
    utter.onstart = () => {
      if (runId !== playRunRef.current) return;
      setSpeaking(true);
      setActiveLine(0);
    };
    utter.onend = () => {
      if (runId !== playRunRef.current) return;
      setSpeaking(false);
      setActiveLine(-1);
      fireDone();
    };
    utter.onerror = () => {
      if (runId !== playRunRef.current) return;
      setSpeaking(false);
      setActiveLine(-1);
      fireDone();
    };
    utteranceRef.current = utter;
    try {
      window.speechSynthesis.speak(utter);
    } catch {
      setSpeaking(false);
    }
  }, [ttsSupported, lines, comfort.enabled, speaker, stop]);

  const speak = useCallback(() => {
    if (mode === "recorded" && blockFile) {
      playRecorded(blockFile);
    } else if (mode === "tts") {
      playTts();
    }
  }, [mode, blockFile, playRecorded, playTts]);

  // Auto-play on mount, ONCE mode has resolved. Slight delay so the
  // screen transition can settle before audio fires.
  const speakRef = useRef(speak);
  speakRef.current = speak;
  const autoFiredRef = useRef(false);
  useEffect(() => {
    // Narration autoplays everywhere by default — the master mute (the HUD
    // speaker button) is the ONLY thing that holds it back.
    if (!NARRATION_AUTOPLAY || !autoPlay) return;
    if (isAudioMuted()) return;
    if (mode === "loading" || mode === "captions") return;
    if (autoFiredRef.current) return;
    autoFiredRef.current = true;
    // Arm the click-guard NOW — we're committed to playing, so the child must
    // not be able to tap through the 400ms pre-roll before the voice sounds.
    // Disarmed the instant `speaking` turns true (see effect below); a 2s
    // backstop guarantees it can never stick if playback fails to start.
    setArmed(true);
    const armBackstop = window.setTimeout(() => setArmed(false), 2000);
    // Fire through a ref, with deps [autoPlay, mode] only (NOT `speak`). If a
    // parent re-renders rapidly while passing an inline `lines` array (e.g. the
    // Choose-Your-Path typewriter re-rendering ~30x/s), `speak`'s identity
    // churns; had it been a dep, each re-run's cleanup would clear this 400ms
    // timer before it fired and the narration would never play.
    const id = window.setTimeout(() => speakRef.current(), 400);
    return () => {
      window.clearTimeout(id);
      window.clearTimeout(armBackstop);
    };
  }, [autoPlay, mode]);

  // Disarm the pre-roll guard once the audio is actually sounding — from here
  // `speaking` keeps the guard up until playback ends/errors/stops.
  useEffect(() => {
    if (speaking) setArmed(false);
  }, [speaking]);

  // Safety release: the click-guard blocks the screen while `speaking`. Some
  // browsers' Web-Speech engine never fires `onend` (a known flake), which
  // would leave `speaking` stuck true and the whole lesson frozen ("can't
  // click anything"). Force playback to end after a generous, length-based
  // max so a child is never trapped behind the guard.
  useEffect(() => {
    if (!speaking) return;
    // Recorded MP3s end reliably via the `ended` event, so their backstop is
    // very generous (never cut a long clip short — that was clipping the last
    // bullet of long narrations). Only the flaky TTS `onend` needs the tight
    // length-based estimate.
    const maxMs =
      mode === "recorded"
        ? 120000
        : Math.min(60000, 6000 + lines.length * 4500);
    // stop() lifts the guard; fireDone() also releases any host gate tied to
    // onDone (e.g. the intro's "button appears when the voice ends"), so a
    // flaky engine that never fires `ended` can't leave the child stuck.
    const id = window.setTimeout(() => { stop(); fireDone(); }, maxMs);
    return () => window.clearTimeout(id);
  }, [speaking, lines.length, stop, fireDone, mode]);

  // Stop when unmounting / navigating away.
  useEffect(() => () => stop(), [stop]);

  // Master mute (HUD button) stops the voice instantly + keeps it off.
  useEffect(() => subscribeAudioMute((muted) => {
    if (muted) stop();
  }), [stop]);

  // Show the audio button whenever EITHER source is usable. In
  // captions-only mode we hide it - there's nothing to play.
  const audioAvailable = mode === "recorded" || mode === "tts";

  return (
    <>
      {/* Block clicks while the narrator speaks so children listen (mute at
          z-index 90 stays reachable and stops narration). Suppressed when the
          host owns the gate (guard=false) to avoid two "listen" indicators. */}
      <NarrationClickGuard active={(speaking || armed) && guard} />
    <div
      style={{
        display: "flex",
        gap: 12,
        alignItems: "flex-start",
        padding: 14,
        background: "rgba(15, 21, 48, 0.65)",
        border: `1px solid ${A}40`,
        borderRadius: 14,
        marginBottom: 16,
      }}
    >
      <div
        aria-hidden
        style={{
          width: 48,
          height: 48,
          minWidth: 48,
          borderRadius: "50%",
          display: "grid",
          placeItems: "center",
          border: `2px solid ${A}`,
          boxShadow: speaking
            ? `0 0 18px ${A}99`
            : `0 0 0 1px ${A}40 inset`,
          background:
            "radial-gradient(circle at 30% 30%, #1a2147 0%, #0a0f24 70%)",
          flexShrink: 0,
          transition: "box-shadow 200ms ease-out",
          fontSize: 22,
          color: A,
          filter: speaking
            ? `drop-shadow(0 0 6px ${A}cc)`
            : undefined,
        }}
      >
        <span>♪</span>
      </div>

      <div style={{ flex: 1, minWidth: 0 }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            marginBottom: 6,
            gap: 8,
          }}
        >
          <span
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontWeight: 800,
              fontSize: 10,
              letterSpacing: "0.14em",
              color: A,
              textTransform: "uppercase",
            }}
          >
            Narration
          </span>
          {/* No manual STOP while speaking — the child can't skip the voice
              (owner 2026-09-07). Only a "Read aloud" replay shows once the
              voice has finished (also the recovery if autoplay was blocked). */}
          {audioAvailable && !speaking && (
            <button
              type="button"
              onClick={speak}
              aria-label="Read aloud"
              style={{
                background: `linear-gradient(135deg, ${A}, ${A}bb)`,
                color: "#04140f",
                border: "none",
                borderRadius: 999,
                padding: "4px 12px",
                fontSize: 12,
                fontWeight: 800,
                cursor: "pointer",
                letterSpacing: "0.04em",
              }}
            >
              ▶ Read aloud
            </button>
          )}
        </div>

        <ul
          style={{
            listStyle: "none",
            padding: 0,
            margin: 0,
            display: "flex",
            flexDirection: "column",
            gap: 6,
            color: "#e7ecff",
            fontFamily:
              "ui-rounded, 'Fredoka', 'Quicksand', system-ui, -apple-system, sans-serif",
            fontSize: 14,
            lineHeight: 1.4,
          }}
        >
          {lines.map((l, i) => (
            <li
              key={i}
              style={{
                paddingLeft: 14,
                position: "relative",
                opacity: activeLine === i ? 1 : speaking ? 0.65 : 1,
                transition: "opacity 200ms ease-out",
              }}
            >
              <span
                aria-hidden
                style={{
                  position: "absolute",
                  left: 0,
                  top: 8,
                  width: 6,
                  height: 6,
                  borderRadius: "50%",
                  background: A,
                  boxShadow: `0 0 6px ${A}99`,
                }}
              />
              {stripTags(l)}
            </li>
          ))}
        </ul>
      </div>
    </div>
    </>
  );
}
