"use client";

/**
 * Narration block for reading-heavy info screens.
 *
 * Plays pre-recorded ElevenLabs MP3s when available (the realistic
 * path), falling back to the browser's Web Speech API only when the
 * manifest is missing the requested lines. The manifest lives at
 * /public/audio/voice/manifest.json and is generated by
 * scripts/elevenlabs-generate-narration.mjs.
 *
 * Audio files play sequentially (one per line) so the on-screen
 * active-line highlight stays in sync with what's being heard, and
 * each file was generated with previous_text/next_text context so
 * prosody flows naturally between lines.
 *
 * If the manifest is missing entries for ANY line in this block, the
 * whole block falls back to Web Speech to avoid a jarring mid-block
 * voice change. If no TTS is available either, the captions are the
 * fallback - the UI stays informative.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { useComfortMode } from "@/app/lib/comfortMode";

// The narration is played via a raw `new Audio()`, which defaults to 1.0
// (FULL volume) - that was the loud blast when a lesson screen opened, so
// it must always be set explicitly. The voice should be clear and dominant
// but comfortable; 0.50 keeps it clearly above the faint music bed (0.03)
// without hurting young ears.
const NARRATION_VOLUME = 0.5;

// Narration auto-plays when a Learn screen opens (back ON now that the
// voice/delivery is approved and the volume is capped + safe). Set to
// `false` for button-only.
const NARRATION_AUTOPLAY = true;

// The narration `lines` carry the SPOKEN script, which includes eleven_v3
// emotional tags like [warmly] / [excited] / [whispers] that direct the
// performed delivery. Those must never appear in the on-screen captions -
// strip anything in square brackets (and tidy spacing) for display only.
function stripTags(line: string): string {
  return line
    .replace(/\[[^\]]*\]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

export interface InfoNarrationProps {
  /** Short lines read in order. Keep each ≤ 12 words. */
  lines: string[];
  /**
   * Voice selection: which character's recorded voice to use. Also
   * drives the synth-voice pitch when falling back to browser TTS.
   */
  speaker?: "adam" | "layla";
  /** Auto-play on mount. Defaults to true; user toggle overrides. */
  autoPlay?: boolean;
}

interface ManifestEntry {
  key: string;
  speaker: "adam" | "layla";
  voice: string;
  /** Full joined block text - the key used at lookup time. */
  text: string;
  /** Original line array for display reference. */
  lines: string[];
  file: string;
}
interface Manifest {
  generatedAt: string;
  model: string;
  chunkStrategy?: "line" | "block";
  entries: ManifestEntry[];
}

const NARRATION_PREF_KEY = "algorithmx-narration-on-v1";
const MANIFEST_URL = "/audio/voice/manifest.json";

function readPref(): boolean {
  if (typeof window === "undefined") return true;
  try {
    const raw = window.localStorage.getItem(NARRATION_PREF_KEY);
    return raw === null ? true : raw === "true";
  } catch {
    return true;
  }
}

function writePref(value: boolean) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(NARRATION_PREF_KEY, String(value));
  } catch {
    /* noop */
  }
}

// Module-level singleton so we fetch the manifest once for the whole
// session, not on every InfoNarration mount. Fetch resolves to null
// if the manifest is missing (404 / network) - in that case we go
// straight to TTS.
let manifestCache: Manifest | null = null;
let manifestPromise: Promise<Manifest | null> | null = null;
async function loadManifest(): Promise<Manifest | null> {
  if (manifestCache) return manifestCache;
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    try {
      // `no-cache` (NOT no-store) so the browser still keeps a copy but
      // always revalidates with the server. Stops a stale, force-cached
      // manifest from pointing at MP3 files that were replaced when the
      // generator was re-run with new voice settings.
      const r = await fetch(MANIFEST_URL, { cache: "no-cache" });
      if (!r.ok) return null;
      const m = (await r.json()) as Manifest;
      manifestCache = m;
      return m;
    } catch {
      return null;
    }
  })();
  return manifestPromise;
}

/**
 * Build the lookup key for a block. Must match exactly how the
 * generator joins the lines (see scripts/elevenlabs-generate-
 * narration.mjs joinBlock()): a single space between lines,
 * collapsed whitespace, trimmed. Keep these two in sync.
 */
function buildBlockKey(lines: string[]): string {
  return lines
    .map((l) => l.trim())
    .filter(Boolean)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

function findBlockEntry(
  manifest: Manifest | null,
  speaker: "adam" | "layla",
  lines: string[],
): ManifestEntry | null {
  if (!manifest) return null;
  const key = buildBlockKey(lines);
  return (
    manifest.entries.find((e) => e.speaker === speaker && e.text === key) ??
    null
  );
}

export default function InfoNarration({
  lines,
  speaker = "adam",
  autoPlay = true,
}: InfoNarrationProps) {
  const comfort = useComfortMode();
  const [enabled, setEnabled] = useState<boolean>(true);
  const [speaking, setSpeaking] = useState<boolean>(false);
  const [activeLine, setActiveLine] = useState<number>(-1);
  // Resolved playback mode for this block. "loading" until the
  // manifest fetch completes; "recorded" if the block has an entry;
  // "tts" if no entry AND browser TTS is available; "captions" if
  // neither is usable (audio button hidden).
  const [mode, setMode] = useState<"loading" | "recorded" | "tts" | "captions">(
    "loading",
  );
  // Recorded-mode: the single block MP3 path. One file = whole block,
  // played as one continuous stream so there are no gaps between
  // sentences (v4-block-flow generator change).
  const [blockFile, setBlockFile] = useState<string | null>(null);
  // Refs for cleanup of in-flight playback.
  const audioElRef = useRef<HTMLAudioElement | null>(null);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);
  // Cancellation token so a re-speak() interrupts the prior sequence
  // without late audio events advancing it.
  const playRunRef = useRef<number>(0);

  const ttsSupported =
    typeof window !== "undefined" && "speechSynthesis" in window;

  useEffect(() => {
    setEnabled(readPref());
  }, []);

  // Resolve mode once the manifest loads.
  useEffect(() => {
    let cancelled = false;
    void loadManifest().then((manifest) => {
      if (cancelled) return;
      const entry = findBlockEntry(manifest, speaker, lines);
      if (entry) {
        setBlockFile(entry.file);
        setMode("recorded");
      } else if (ttsSupported) {
        setMode("tts");
      } else {
        setMode("captions");
      }
    });
    return () => {
      cancelled = true;
    };
  }, [lines, speaker, ttsSupported]);

  /* ────── Stop both pipelines cleanly ────── */
  const stop = useCallback(() => {
    playRunRef.current++; // invalidate any in-flight sequence
    // Recorded
    if (audioElRef.current) {
      try {
        audioElRef.current.pause();
        audioElRef.current.src = "";
      } catch {
        /* noop */
      }
      audioElRef.current = null;
    }
    // TTS
    if (ttsSupported) {
      try {
        window.speechSynthesis.cancel();
      } catch {
        /* noop */
      }
    }
    setSpeaking(false);
    setActiveLine(-1);
  }, [ttsSupported]);

  /* ────── Recorded playback: one continuous block-level MP3 ────── */
  const playRecorded = useCallback(
    (file: string) => {
      stop();
      const runId = ++playRunRef.current;
      setSpeaking(true);
      // No per-line active highlight under recorded mode - the whole
      // block plays as one continuous audio, so highlighting a single
      // bullet at a time would lie about what's being heard. All
      // bullets stay at full opacity during playback.
      setActiveLine(-1);

      const el = new Audio(file);
      el.preload = "auto";
      el.volume = NARRATION_VOLUME; // never the raw 1.0 default - see constant
      audioElRef.current = el;
      el.addEventListener(
        "ended",
        () => {
          if (runId !== playRunRef.current) return;
          setSpeaking(false);
          audioElRef.current = null;
        },
        { once: true },
      );
      el.addEventListener(
        "error",
        () => {
          if (runId !== playRunRef.current) return;
          setSpeaking(false);
          audioElRef.current = null;
        },
        { once: true },
      );
      // Browsers may reject autoplay without a user gesture; we
      // swallow the rejection - the toggle button is the gesture
      // path so the next user tap will succeed.
      el.play().catch(() => {
        if (runId !== playRunRef.current) return;
        setSpeaking(false);
        audioElRef.current = null;
      });
    },
    [stop],
  );

  /* ────── TTS fallback (one utterance per block) ────── */
  const playTts = useCallback(() => {
    if (!ttsSupported || lines.length === 0) return;
    stop();
    const runId = ++playRunRef.current;
    const text = lines.join(". ");
    const utter = new SpeechSynthesisUtterance(text);
    utter.rate = comfort.enabled ? 0.9 : 1.0;
    utter.pitch = speaker === "layla" ? 1.15 : 0.95;
    utter.volume = 1;
    utter.onstart = () => {
      if (runId !== playRunRef.current) return;
      setSpeaking(true);
      setActiveLine(0);
    };
    utter.onend = () => {
      if (runId !== playRunRef.current) return;
      setSpeaking(false);
      setActiveLine(-1);
    };
    utter.onerror = () => {
      if (runId !== playRunRef.current) return;
      setSpeaking(false);
      setActiveLine(-1);
    };
    utteranceRef.current = utter;
    try {
      window.speechSynthesis.speak(utter);
    } catch {
      setSpeaking(false);
    }
  }, [ttsSupported, lines, comfort.enabled, speaker, stop]);

  const speak = useCallback(() => {
    if (mode === "recorded" && blockFile) {
      playRecorded(blockFile);
    } else if (mode === "tts") {
      playTts();
    }
  }, [mode, blockFile, playRecorded, playTts]);

  // Auto-play on mount, ONCE mode has resolved. Slight delay so the
  // screen transition can settle before audio fires.
  const autoFiredRef = useRef(false);
  useEffect(() => {
    if (!NARRATION_AUTOPLAY || !autoPlay || !enabled) return;
    if (mode === "loading" || mode === "captions") return;
    if (autoFiredRef.current) return;
    autoFiredRef.current = true;
    const id = window.setTimeout(speak, 400);
    return () => window.clearTimeout(id);
  }, [autoPlay, enabled, mode, speak]);

  // Stop when unmounting / navigating away.
  useEffect(() => () => stop(), [stop]);

  const toggleEnabled = () => {
    const next = !enabled;
    setEnabled(next);
    writePref(next);
    if (!next) stop();
    else speak();
  };

  // Show the audio button whenever EITHER source is usable. In
  // captions-only mode we hide it - there's nothing to play.
  const audioAvailable = mode === "recorded" || mode === "tts";

  return (
    <div
      style={{
        display: "flex",
        gap: 12,
        alignItems: "flex-start",
        padding: 14,
        background: "rgba(15, 21, 48, 0.65)",
        border: "1px solid rgba(125, 240, 255, 0.25)",
        borderRadius: 14,
        marginBottom: 16,
      }}
    >
      <div
        aria-hidden
        style={{
          width: 48,
          height: 48,
          minWidth: 48,
          borderRadius: "50%",
          display: "grid",
          placeItems: "center",
          border: "2px solid #7df0ff",
          boxShadow: speaking
            ? "0 0 18px rgba(125, 240, 255, 0.6)"
            : "0 0 0 1px rgba(125, 240, 255, 0.25) inset",
          background:
            "radial-gradient(circle at 30% 30%, #1a2147 0%, #0a0f24 70%)",
          flexShrink: 0,
          transition: "box-shadow 200ms ease-out",
          fontSize: 22,
          color: "#7df0ff",
          filter: speaking
            ? "drop-shadow(0 0 6px rgba(125, 240, 255, 0.8))"
            : undefined,
        }}
      >
        <span>♪</span>
      </div>

      <div style={{ flex: 1, minWidth: 0 }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            marginBottom: 6,
            gap: 8,
          }}
        >
          <span
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontWeight: 800,
              fontSize: 10,
              letterSpacing: "0.14em",
              color: "#7df0ff",
              textTransform: "uppercase",
            }}
          >
            Narration
          </span>
          {audioAvailable && (
            <button
              type="button"
              onClick={speaking ? stop : speak}
              aria-label={speaking ? "Stop narration" : "Read aloud"}
              style={{
                background: speaking
                  ? "linear-gradient(135deg, #ff5fb3, #7c5cff)"
                  : "linear-gradient(135deg, #00e5ff, #7c5cff)",
                color: "#fff",
                border: "none",
                borderRadius: 999,
                padding: "4px 12px",
                fontSize: 12,
                fontWeight: 800,
                cursor: "pointer",
                letterSpacing: "0.04em",
              }}
            >
              {speaking ? "■ Stop" : "▶ Read aloud"}
            </button>
          )}
        </div>

        <ul
          style={{
            listStyle: "none",
            padding: 0,
            margin: 0,
            display: "flex",
            flexDirection: "column",
            gap: 6,
            color: "#e7ecff",
            fontFamily:
              "ui-rounded, 'Fredoka', 'Quicksand', system-ui, -apple-system, sans-serif",
            fontSize: 14,
            lineHeight: 1.4,
          }}
        >
          {lines.map((l, i) => (
            <li
              key={i}
              style={{
                paddingLeft: 14,
                position: "relative",
                opacity: activeLine === i ? 1 : speaking ? 0.65 : 1,
                transition: "opacity 200ms ease-out",
              }}
            >
              <span
                aria-hidden
                style={{
                  position: "absolute",
                  left: 0,
                  top: 8,
                  width: 6,
                  height: 6,
                  borderRadius: "50%",
                  background: "#7df0ff",
                  boxShadow: "0 0 6px rgba(125, 240, 255, 0.6)",
                }}
              />
              {stripTags(l)}
            </li>
          ))}
        </ul>

        {audioAvailable && (
          <button
            type="button"
            onClick={toggleEnabled}
            style={{
              marginTop: 8,
              background: "transparent",
              border: "none",
              color: "#94a3b8",
              fontSize: 11,
              cursor: "pointer",
              padding: 0,
              textDecoration: "underline",
            }}
          >
            {enabled ? "Auto-read is on" : "Auto-read is off"}
          </button>
        )}
      </div>
    </div>
  );
}
