import type { WeekIntroContent } from "./types";

/**
 * Per-week "Mission Command" briefings, narrated by ATLAS (ElevenLabs "Daniel",
 * eleven_v3, flowing script). One entry per week; each week file spreads its
 * entry into a { type: "weekIntro" } screen placed right after the intro video.
 * The narration mp3s are generated by scripts/generate-atlas-weekintros.mjs
 * into /public/audio/atlas/heroes-week-NN.mp3. Every chip emoji is one that
 * PixIcon has a real 3D icon for (no raw-emoji fallback).
 */
export const WEEK_INTROS: Record<number, WeekIntroContent> = {
  1: {
    title: "Passwords: The Secret Code",
    tagline: "Learn the magic words that keep the Hacker Raccoon locked out.",
    audioSrc: "/audio/atlas/heroes-week-01.mp3",
    accent: "#e3b341",
    points: [
      { icon: "🔑", label: "Build a strong password" },
      { icon: "🤫", label: "Keep it secret" },
      { icon: "🦝", label: "Beat the Hacker Raccoon" },
    ],
  },
  2: {
    title: "Private Info: Guard Your Secrets",
    tagline: "Some things you can share, and some you keep locked away.",
    audioSrc: "/audio/atlas/heroes-week-02.mp3",
    accent: "#9d7bff",
    points: [
      { icon: "🆔", label: "Spot your secrets" },
      { icon: "🔒", label: "Lock them away" },
      { icon: "✅", label: "Share the safe stuff" },
    ],
  },
  3: {
    title: "Stranger Danger: Friend or Foe?",
    tagline: "Online, not everyone is who they say they are.",
    audioSrc: "/audio/atlas/heroes-week-03.mp3",
    accent: "#f5a623",
    points: [
      { icon: "🕵️", label: "Spot a fake friend" },
      { icon: "🚫", label: "Don't share with strangers" },
      { icon: "💬", label: "Tell a grown-up" },
    ],
  },
  4: {
    title: "Scams and Tricks: Real or Fake?",
    tagline: "Spot the trick, and the trick can't touch you.",
    audioSrc: "/audio/atlas/heroes-week-04.mp3",
    accent: "#e84dff",
    points: [
      { icon: "🎁", label: "Follow the string, measure the bait" },
      { icon: "🔔", label: "Feel the rush, then slow down" },
      { icon: "✋", label: "Stop, check, show a grown-up" },
    ],
  },
  5: {
    title: "Cyberbullying: Words Have Power",
    tagline: "Be the kind one, and stop the bullies cold.",
    audioSrc: "/audio/atlas/heroes-week-05.mp3",
    accent: "#ff8e6e",
    points: [
      { icon: "💬", label: "Be kind" },
      { icon: "🦸", label: "Stand up for others" },
      { icon: "🔔", label: "Tell someone" },
    ],
  },
  6: {
    title: "Gaming Safety: Defend Your Game Zone",
    tagline: "Every game zone needs a guard.",
    audioSrc: "/audio/atlas/heroes-week-06.mp3",
    accent: "#ff3cb4",
    points: [
      { icon: "🎮", label: "Guard your game" },
      { icon: "🚫", label: "Block strangers" },
      { icon: "🔒", label: "Protect your account" },
    ],
  },
  7: {
    title: "In-Game Spending: The Gem Bucks Trap",
    tagline: "Every shiny coin costs real money.",
    audioSrc: "/audio/atlas/heroes-week-07.mp3",
    accent: "#ff4e6a",
    points: [
      { icon: "💎", label: "Count coins as real money" },
      { icon: "⏸️", label: "Freeze the countdown" },
      { icon: "👪", label: "Ask before you buy" },
    ],
  },
  8: {
    title: "Photos & Videos: Think Before You Share",
    tagline: "Once a photo is out, it's hard to bring back.",
    audioSrc: "/audio/atlas/heroes-week-08.mp3",
    accent: "#ff6b3d",
    points: [
      { icon: "📸", label: "Think before you share" },
      { icon: "🔍", label: "Check every corner" },
      { icon: "💬", label: "Ask every face" },
    ],
  },
  9: {
    title: "Apps & Downloads: Spot the Fakes",
    tagline: "Not every app is what it pretends to be.",
    audioSrc: "/audio/atlas/heroes-week-09.mp3",
    accent: "#2b7fff",
    points: [
      { icon: "📱", label: "Real shop only" },
      { icon: "🔍", label: "Count the whiskers" },
      { icon: "👪", label: "Install together" },
    ],
  },
  10: {
    title: "Videos & Channels: Escape the Rabbit Hole",
    tagline: "You choose when to stop, not the screen.",
    audioSrc: "/audio/atlas/heroes-week-10.mp3",
    accent: "#b8e34b",
    points: [
      { icon: "🔀", label: "Spot the belt" },
      { icon: "📏", label: "Weigh the claim" },
      { icon: "⏸️", label: "Hold the pause" },
    ],
  },
  11: {
    title: "Something Wrong? Emergency Protocol",
    tagline: "When something feels wrong, here's what to do.",
    audioSrc: "/audio/atlas/heroes-week-11.mp3",
    accent: "#ff9528",
    points: [
      { icon: "💪", label: "Never your fault" },
      { icon: "👪", label: "Name your team" },
      { icon: "🚀", label: "Run the drill" },
    ],
  },
  12: {
    title: "Digital Footprint: Tracks in the Snow",
    tagline: "Out here the snow keeps every print you leave.",
    audioSrc: "/audio/atlas/heroes-week-12.mp3",
    accent: "#a8e4ff",
    points: [
      { icon: "💡", label: "See the print behind every tap" },
      { icon: "👀", label: "Ask what older you would think" },
      { icon: "🥇", label: "Stamp the trail you want found" },
    ],
  },
  13: {
    title: "Screen Time: Balance Your Power",
    tagline: "Even heroes need to recharge.",
    audioSrc: "/audio/atlas/heroes-week-13.mp3",
    accent: "#2ec4b6",
    points: [
      { icon: "⚡", label: "Recharge your power" },
      { icon: "⏱️", label: "Know when to stop" },
      { icon: "💪", label: "Find balance" },
    ],
  },
  14: {
    title: "Smart Devices: Who's Listening?",
    tagline: "Some gadgets have ears and eyes.",
    audioSrc: "/audio/atlas/heroes-week-14.mp3",
    accent: "#45e3ff",
    points: [
      { icon: "🔔", label: "Who's listening?" },
      { icon: "👀", label: "Who's watching?" },
      { icon: "🤫", label: "Guard your secrets" },
    ],
  },
  15: {
    title: "AI & Chatbots: Robot or Real?",
    tagline: "Some voices online aren't people at all.",
    audioSrc: "/audio/atlas/heroes-week-15.mp3",
    accent: "#3dffc4",
    points: [
      { icon: "🤖", label: "Robot or real?" },
      { icon: "❓", label: "Check the facts" },
      { icon: "🤫", label: "Don't overshare" },
    ],
  },
  16: {
    title: "QR Codes & Links: Don't Take the Bait",
    tagline: "A link is a doorway, so look before you leap.",
    audioSrc: "/audio/atlas/heroes-week-16.mp3",
    accent: "#b44dff",
    points: [
      { icon: "🔗", label: "Check the link" },
      { icon: "🔍", label: "Look before you tap" },
      { icon: "🪤", label: "Don't take the bait" },
    ],
  },
  17: {
    title: "Social Media: The Profile Shield",
    tagline: "Raise your shield and share a little less.",
    audioSrc: "/audio/atlas/heroes-week-17.mp3",
    accent: "#38b6ff",
    points: [
      { icon: "🛡️", label: "Shield your profile" },
      { icon: "👤", label: "Followers aren't friends" },
      { icon: "🔒", label: "Go private" },
    ],
  },
  18: {
    title: "Sharing Devices: Lock Before You Leave",
    tagline: "Using a device that isn't yours? Lock up.",
    audioSrc: "/audio/atlas/heroes-week-18.mp3",
    accent: "#62b6cb",
    points: [
      { icon: "🚪", label: "Log out" },
      { icon: "🔑", label: "Keep your keys" },
      { icon: "🤫", label: "Respect privacy" },
    ],
  },
  19: {
    title: "Protecting Family: Family Firewall",
    tagline: "Now protect the people you love.",
    audioSrc: "/audio/atlas/heroes-week-19.mp3",
    accent: "#ffb26b",
    points: [
      { icon: "👪", label: "Protect your family" },
      { icon: "🔒", label: "Build the firewall" },
      { icon: "🕵️", label: "Spot the tricks" },
    ],
  },
  20: {
    title: "Graduation Day: The Final Mission",
    tagline: "Everything you've learned, all at once.",
    audioSrc: "/audio/atlas/heroes-week-20.mp3",
    accent: "#5b76ff",
    points: [
      { icon: "🎓", label: "Graduate" },
      { icon: "🏆", label: "Final mission" },
      { icon: "🦝", label: "Beat the Raccoon" },
    ],
  },
};
