import type { WeekContent } from "./types";

export const WEEK_3: WeekContent = {
  weekNumber: 3,
  title: "Stranger Danger: Friend or Foe?",
  topic: "stranger-danger",
  badgeName: "Stranger Spotter",
  badgeIcon: "🔍",

  introCutscene: [
    { text: "CYBER HEROES ACADEMY\nWEEK 3: STRANGER DANGER", bg: "normal", duration: 3000 },
    { character: "both", characterMood: "excited", text: "Welcome back, Cyber Hero! This week is REALLY important.", sound: "lessonStart", duration: 5000 },
    { character: "layla", characterMood: "worried", text: "Hacker Raccoon has a new trick. He's pretending to be a kid online to trick REAL kids into sharing their secrets!", bg: "danger", sound: "bossRoar", duration: 5500 },
    { character: "raccoon", characterMood: "idle", text: "\"Hey there! I'm totally a 10-year-old just like you! Want to be best friends? Just tell me where you live!\"", textColour: "#c084fc", duration: 5500 },
    { character: "adam", characterMood: "thinking", text: "See? Online, you can NEVER be sure who you're really talking to. Someone might not be who they say they are.", duration: 5500 },
    { character: "layla", characterMood: "excited", text: "But don't worry! Today we're going to learn how to spot fake friends and stay safe from online strangers!", duration: 5000 },
    { character: "adam", characterMood: "thumbsup", text: "Remember — a REAL friend would never ask you to keep secrets from your parents. Let's go!", sound: "select", duration: 5000 },
    { text: "LET'S GO! 🚀", bg: "normal", sound: "confetti", duration: 2000 },
  ],

  screens: [
    { type: "video", videoPlaceholder: "Week 3: Stranger Danger intro video" },
    {
      type: "mission",
      objectives: [
        "Learn who is a stranger online",
        "Spot tricks that online strangers use",
        "Know what to do if a stranger contacts you",
      ],
    },
    {
      type: "info",
      title: "Who Is a Stranger Online?",
      content:
        "A stranger is ANYONE you haven't met in real life. Even if they seem nice, funny, or say they're your age — if you've never met them face to face, they're a stranger. Online, people can pretend to be ANYONE.",
      bullets: [
        "They might use a fake name",
        "They might use a fake photo",
        "They might pretend to be a kid when they're an adult",
        "They might say they know your friends when they don't",
      ],
    },
    {
      type: "cyberScanner",
      items: [
        { text: "A new person says 'I'm 10, just like you!'", isStrong: false, explanation: "You can't verify someone's age online — they could be anyone" },
        { text: "Your teacher at school", isStrong: true, explanation: "Someone you know in real life and can trust" },
        { text: "A person offering free V-Bucks if you chat", isStrong: false, explanation: "Strangers use gifts/bribes to gain trust — it's a trick" },
        { text: "Your mum on FaceTime", isStrong: true, explanation: "Someone you know and can see face-to-face" },
        { text: "A gaming friend you've never met", isStrong: false, explanation: "Even nice online friends are still strangers if you've never met them" },
        { text: "Your cousin who lives far away", isStrong: true, explanation: "Family you know in real life — even if they're far away" },
        { text: "Someone asking for your photo", isStrong: false, explanation: "A stranger asking for photos is a big red flag" },
        { text: "A friend from school on WhatsApp", isStrong: true, explanation: "Someone you know and see in person" },
        { text: "A person who says 'Don't tell your parents'", isStrong: false, explanation: "ANYONE who says this is dangerous — always tell a trusted adult" },
        { text: "Your swimming instructor", isStrong: true, explanation: "A trusted adult you know in real life" },
      ],
    },
    {
      type: "info",
      title: "Stranger Danger Tricks",
      content: "Online strangers use sneaky tricks to gain your trust. Here are the most common ones:",
      bullets: [
        "Flattery: 'You're so smart/cool/talented!'",
        "Gifts: 'I'll give you free game items!'",
        "Secrets: 'Don't tell your parents about our chat'",
        "Urgency: 'You have to reply RIGHT NOW!'",
        "Fake identity: 'I go to your school too!'",
      ],
    },
    {
      type: "chooseYourPath",
      scenarios: [
        {
          setup: "Someone you don't know sends you a friend request on a game. They say 'I heard you're really good — let's play together!'",
          choices: [
            { text: "Accept and start playing with them", isSafe: false, consequence: "This person is a stranger. They could be anyone pretending to be a kid. You've given them access to your profile." },
            { text: "Ignore the request and tell a parent", isSafe: true, consequence: "Smart! You don't know this person. A real friend would talk to you in person first." },
          ],
        },
        {
          setup: "An online friend you've never met says 'Let's meet up at the park! Don't tell anyone — it'll be a surprise!'",
          choices: [
            { text: "Go meet them — they seem nice", isSafe: false, consequence: "NEVER meet an online stranger alone! Someone who says 'don't tell anyone' is a huge red flag." },
            { text: "Say no and immediately tell a parent", isSafe: true, consequence: "Perfect! You should NEVER meet someone from the internet without a trusted adult, and ALWAYS tell your parents." },
          ],
        },
        {
          setup: "A person in a game chat asks 'What school do you go to? I bet I live near you!'",
          choices: [
            { text: "Tell them — maybe you can be real friends", isSafe: false, consequence: "Never share your school name online! A stranger could use it to find you in real life." },
            { text: "Don't answer and change the subject", isSafe: true, consequence: "Great thinking! Your school is private information. Real friends don't need to know it from a game chat." },
          ],
        },
        {
          setup: "Someone online sends you a really cool game link and says 'You HAVE to try this — but don't show it to your parents, they'll say no'",
          choices: [
            { text: "Click the link — it looks fun", isSafe: false, consequence: "Links from strangers can contain viruses or lead to dangerous websites. And anyone who says 'don't tell your parents' is not trustworthy." },
            { text: "Don't click it and tell a parent", isSafe: true, consequence: "Smart move! Never click links from strangers, and always tell a trusted adult when someone says to keep secrets from your parents." },
          ],
        },
      ],
    },
    {
      type: "memoryMatch",
      pairs: [
        { term: "Stranger", match: "Someone you've never met in real life", colour: "#ef4444" },
        { term: "Red Flag", match: "'Don't tell your parents'", colour: "#f97316" },
        { term: "Grooming", match: "When strangers slowly gain your trust", colour: "#8b5cf6" },
        { term: "Trusted Adult", match: "Parent, teacher, or family member", colour: "#34d399" },
        { term: "Catfishing", match: "Pretending to be someone you're not", colour: "#60a5fa" },
        { term: "Safe Response", match: "Block, report, tell an adult", colour: "#fbbf24" },
      ],
    },
    {
      type: "info",
      title: "The 3 Safety Rules",
      content: "If a stranger contacts you online, remember these three rules:",
      bullets: [
        "BLOCK them straight away",
        "REPORT them using the app's report button",
        "TELL a trusted adult (parent, teacher, older sibling) immediately",
      ],
    },
    {
      type: "protectTheData",
      items: [
        { text: "Your home address", isPrivate: true },
        { text: "Your favourite colour", isPrivate: false },
        { text: "Your school name", isPrivate: true },
        { text: "Your full name", isPrivate: true },
        { text: "Your favourite game", isPrivate: false },
        { text: "What time you walk home", isPrivate: true },
        { text: "Your favourite food", isPrivate: false },
        { text: "Your phone number", isPrivate: true },
        { text: "Your favourite animal", isPrivate: false },
        { text: "Photos of yourself", isPrivate: true },
        { text: "Your age (I'm a kid)", isPrivate: false },
        { text: "Your parents' names", isPrivate: true },
      ],
    },
    {
      type: "firewallBuilder",
      goodBlocks: [
        "Block strangers",
        "Tell a trusted adult",
        "Keep personal info private",
        "Report suspicious people",
        "Only chat with people you know IRL",
        "Never meet online strangers alone",
        "Check with parents first",
        "Use privacy settings",
      ],
      badBlocks: [
        "Share your address",
        "Meet strangers alone",
        "Keep secrets from parents",
        "Send photos to strangers",
      ],
    },
    {
      type: "spamBlaster",
      emails: [
        { sender: "CoolKid2015", subject: "Hey! I'm 10 too! Want to be best friends?", isPhishing: true, clue: "Strangers claiming to be your age — you can't verify this" },
        { sender: "Mum", subject: "Don't forget your packed lunch tomorrow!", isPhishing: false, clue: "" },
        { sender: "GameMaster99", subject: "You won! Send me your address for your free prize!", isPhishing: true, clue: "Asking for your address is a huge red flag" },
        { sender: "Mrs Patterson", subject: "Homework due Thursday — don't forget!", isPhishing: false, clue: "" },
        { sender: "Mystery Friend", subject: "I know where you go to school. Want to meet up?", isPhishing: true, clue: "Someone claiming to know you who you don't recognise — very dangerous" },
        { sender: "Dad", subject: "Football practice moved to 4pm Saturday", isPhishing: false, clue: "" },
        { sender: "SecretAdmirer", subject: "You're so cool! Send me a selfie!", isPhishing: true, clue: "Never send photos to people you don't know" },
        { sender: "Best Friend Sam", subject: "LOL did you see what happened at lunch?", isPhishing: false, clue: "" },
        { sender: "GiftGiver2024", subject: "FREE Roblox gift card! Just tell me your username and password!", isPhishing: true, clue: "Asking for passwords is always a scam" },
        { sender: "Grandma", subject: "Can't wait to see you this weekend!", isPhishing: false, clue: "" },
      ],
    },
    {
      type: "cyberMaze",
      questions: [
        { question: "What should you do if a stranger contacts you online?", answers: ["Block, report, and tell a trusted adult", "Chat with them to be polite", "Send them a photo", "Give them your number"], correctIndex: 0 },
        { question: "Why might someone pretend to be a kid online?", answers: ["To trick real kids into trusting them", "Because they're bored", "To play games", "To help with homework"], correctIndex: 0 },
        { question: "Which is a red flag from an online stranger?", answers: ["'Don't tell your parents about our chat'", "'What's your favourite game?'", "'Have a nice day!'", "'Good luck in your match!'"], correctIndex: 0 },
        { question: "Is it safe to meet an online friend in person?", answers: ["Never without a trusted adult present", "Yes if they seem nice", "Only at a public place", "Yes if you've chatted for a long time"], correctIndex: 0 },
        { question: "A stranger offers you free V-Bucks. What's really happening?", answers: ["They're trying to trick you into sharing information", "They're being generous", "They're a game developer", "They won a competition"], correctIndex: 0 },
      ],
    },
    { type: "bossBattle" },
    { type: "completion" },
  ],

  bossQuestions: {
    easy: [
      { question: "Who is a stranger online?", answers: ["Anyone you haven't met in real life", "Someone who is mean", "Someone from another country", "Someone without a photo"], correctIndex: 0, explanation: "A stranger is ANYONE you haven't met face-to-face, even if they seem friendly" },
      { question: "Should you share your address with someone you met in a game?", answers: ["Yes if they're nice", "Never", "Only if they share theirs first", "Only in private chat"], correctIndex: 1, explanation: "Never share your address with anyone online — you don't know who they really are" },
      { question: "Someone online says 'Don't tell your parents.' What should you do?", answers: ["Keep the secret", "Tell a parent immediately", "Tell a friend instead", "Ignore it"], correctIndex: 1, explanation: "ANYONE who says this is not trustworthy — always tell a trusted adult" },
      { question: "What is catfishing?", answers: ["A fishing game", "Pretending to be someone you're not online", "Catching fish with a cat", "A type of virus"], correctIndex: 1, explanation: "Catfishing means creating a fake identity to trick people online" },
      { question: "Which person is safe to trust?", answers: ["Online friend you've never met", "Your teacher at school", "Someone who gives you gifts online", "A popular gamer"], correctIndex: 1, explanation: "Only trust people you know in real life, like your teacher" },
      { question: "A stranger says 'I'm 10 years old, just like you!' Is this definitely true?", answers: ["Yes, people don't lie about their age", "No, you can't verify someone's age online", "Yes if they have a kid's profile picture", "Yes if they play kid's games"], correctIndex: 1, explanation: "You can never be sure how old someone really is online" },
      { question: "What are the 3 safety rules for stranger danger?", answers: ["Run, hide, fight", "Block, report, tell an adult", "Delete, ignore, forget", "Like, share, subscribe"], correctIndex: 1, explanation: "Block the person, report them, and tell a trusted adult" },
      { question: "Is it OK to send a photo of yourself to someone you met online?", answers: ["Yes if they ask nicely", "Yes if they sent one first", "Never", "Only a funny one"], correctIndex: 2, explanation: "Never send photos to people you don't know in real life" },
      { question: "A gaming friend wants to voice chat. What should you do?", answers: ["Join immediately", "Ask a parent first", "Give them your phone number", "Share your social media"], correctIndex: 1, explanation: "Always check with a parent before voice chatting with people online" },
      { question: "Why do online strangers sometimes give gifts or compliments?", answers: ["They're just being nice", "To gain your trust so they can trick you", "They have too much money", "It's normal online behaviour"], correctIndex: 1, explanation: "Strangers use flattery and gifts to build trust — it's a trick called grooming" },
    ],
    medium: [
      { question: "What is 'grooming' in online safety?", answers: ["Brushing your hair", "When strangers slowly build trust to manipulate you", "Making your profile look nice", "Cleaning up your messages"], correctIndex: 1, explanation: "Grooming is when someone gradually gains your trust to exploit you later" },
      { question: "Which scenario is the BIGGEST red flag?", answers: ["A friend sharing a meme", "A stranger saying 'Let's keep this between us'", "Your mum asking about your day", "A teacher sending homework"], correctIndex: 1, explanation: "Secrecy is the biggest danger sign — real friends don't ask you to keep secrets from parents" },
      { question: "Someone you only know online asks 'What time does school finish?' Why is this dangerous?", answers: ["It's not dangerous, it's just a question", "They could use it to find out where you are and when", "They want to help with homework", "They're just curious"], correctIndex: 1, explanation: "Knowing your schedule helps a stranger predict where you'll be — very dangerous" },
      { question: "How can you tell if an online profile is fake?", answers: ["You can always tell", "You can't always tell — that's why you should be careful with everyone", "Fake profiles always have no photos", "Fake profiles always have weird names"], correctIndex: 1, explanation: "Fake profiles can look completely real — that's why you should treat all online strangers with caution" },
      { question: "What should you do if a stranger makes you feel uncomfortable online?", answers: ["Try to be polite and keep chatting", "Tell them to stop and hope they do", "Block them, save evidence, and tell a trusted adult", "Delete the app and forget about it"], correctIndex: 2, explanation: "Block them, screenshot the evidence, and tell a trusted adult immediately" },
      { question: "A stranger says they go to a school near yours. Should you believe them?", answers: ["Yes, why would they lie?", "No, this could be a trick to seem trustworthy", "Ask them to prove it", "Only if they know your teacher's name"], correctIndex: 1, explanation: "Claiming to be local is a common trick to build false trust" },
      { question: "Why shouldn't you share your location in social media posts?", answers: ["It uses too much battery", "Strangers could use it to find you in real life", "It makes your phone slow", "It's against the rules"], correctIndex: 1, explanation: "Sharing your location tells everyone — including strangers — exactly where you are" },
      { question: "A person online says 'I work for Roblox. Give me your account to get free Robux.' What should you do?", answers: ["Give them your account — free Robux!", "Ask them to prove it", "Report them — real Roblox staff would never ask for this", "Tell your friends about the offer"], correctIndex: 2, explanation: "No real game company employee would ever ask for your account details in a chat" },
      { question: "Is it safe to join a private chat room that a stranger invited you to?", answers: ["Yes if other kids are in it", "No — private chats are harder for adults to monitor and strangers may try to isolate you", "Only if it's on a popular app", "Yes if the stranger seems nice"], correctIndex: 1, explanation: "Strangers use private chats to isolate kids away from safety features and moderation" },
      { question: "What information can a stranger get just from your username?", answers: ["Nothing at all", "Sometimes your real name, age, or interests if it contains them", "Only your email", "Your password"], correctIndex: 1, explanation: "A username like 'Emma2014London' reveals your name, birth year, and city — choose usernames carefully" },
    ],
    hard: [
      { question: "Your online friend of 6 months asks to meet in person. They've always been kind. What should you do?", answers: ["Meet them — you've known them long enough", "Meet in a public place just to be safe", "Only agree if a trusted adult comes with you AND your parents approve", "Ask them to video call first, then meet"], correctIndex: 2, explanation: "Even after months of chatting, you don't truly know someone online. NEVER meet without a trusted adult present AND parental permission" },
      { question: "A stranger sends you a screenshot of your school from Google Maps. What does this mean?", answers: ["They go to your school too", "They've been researching where you are — this is very dangerous", "It's just a coincidence", "They're showing off their Google skills"], correctIndex: 1, explanation: "A stranger who researches your location is dangerous — tell a trusted adult immediately" },
      { question: "Why do some predators spend weeks being friendly before asking for anything?", answers: ["They're genuinely nice people", "They're building trust so you'll do what they ask later (grooming)", "They're just slow at typing", "They want to be real friends"], correctIndex: 1, explanation: "Grooming is a deliberate process of building trust over time to manipulate someone" },
      { question: "A stranger offers to help you get better at a game. They want to TeamViewer into your computer. What's the risk?", answers: ["They might play better than you", "They'd have complete control of your computer — seeing passwords, files, and personal data", "There's no risk if you watch the screen", "They might change your game settings"], correctIndex: 1, explanation: "Remote access gives someone control over your entire computer — never allow this with someone you don't know" },
      { question: "You see your younger sibling chatting with a stranger online who's asking personal questions. What should you do?", answers: ["Mind your own business", "Tell a parent or trusted adult immediately", "Tell the stranger to go away yourself", "Let your sibling handle it — they'll learn"], correctIndex: 1, explanation: "Always tell a trusted adult when you see someone younger being targeted — don't try to handle it alone" },
      { question: "A popular influencer you follow DMs you privately asking to 'be friends' and chat. What should you think?", answers: ["Amazing! I'm so lucky!", "Real influencers rarely DM random followers — this could be a fake account", "They probably DM all their followers", "Accept and see what they want"], correctIndex: 1, explanation: "Fake accounts often impersonate influencers to gain trust — real celebrities don't randomly DM children" },
      { question: "Someone in a game lobby shares a Discord server invite and says 'it's just for cool kids — no adults allowed.' What's the concern?", answers: ["It sounds fun and exclusive", "Unmoderated servers without adults are exactly where predators target children", "It's fine because it's just Discord", "Only go if your friends are there too"], correctIndex: 1, explanation: "Spaces with no adult moderation are unsafe — predators specifically seek out child-only spaces" },
      { question: "What should you do if a stranger threatens to share embarrassing information about you unless you do what they say?", answers: ["Do what they say to avoid embarrassment", "Delete your account and hope they go away", "Tell a trusted adult IMMEDIATELY — this is blackmail and it's a crime", "Try to negotiate with them"], correctIndex: 2, explanation: "This is blackmail/extortion — a serious crime. Tell a trusted adult immediately, no matter what they threaten" },
      { question: "A stranger finds your social media through a mutual friend's tagged photo. How did this happen?", answers: ["Your friend's privacy settings allowed it", "The stranger hacked your friend", "Social media is always private", "Photos can't be tagged"], correctIndex: 0, explanation: "Tagged photos can reveal your identity to strangers through your friends' profiles — check your tag settings" },
      { question: "What makes 'online-only' friendships riskier than real-life ones?", answers: ["They're not riskier at all", "Online you can't verify identity, body language, or true intentions — people can be anyone", "Real-life friends are more boring", "There's no difference"], correctIndex: 1, explanation: "In person, you can see, hear, and verify who someone is. Online, everything can be faked" },
    ],
  },

  reactions: {
    0: { adam: { mood: "excited", message: "Welcome to Week 3! This one's really important." }, layla: null },
    1: { adam: null, layla: { mood: "curious", message: "Let's learn about staying safe from strangers online." } },
    2: { adam: { mood: "thinking", message: "Remember — online, people can pretend to be anyone." }, layla: null },
    3: { adam: null, layla: { mood: "excited", message: "Can you tell the difference between strangers and safe people?" } },
    4: { adam: { mood: "worried", message: "These tricks are sneaky! Watch out for them." }, layla: null },
    5: { adam: null, layla: { mood: "thinking", message: "What would YOU do in these situations?" } },
    6: { adam: { mood: "curious", message: "Match up the stranger danger terms!" }, layla: null },
    7: { adam: null, layla: { mood: "thumbsup", message: "Block, Report, Tell — the 3 safety rules!" } },
    8: { adam: { mood: "excited", message: "Protect your private data from strangers!" }, layla: null },
    9: { adam: null, layla: { mood: "excited", message: "Build your firewall of safety!" } },
    10: { adam: { mood: "worried", message: "Watch out for those fake messages!" }, layla: null },
    11: { adam: null, layla: { mood: "excited", message: "Navigate the maze and answer the questions!" } },
    12: { adam: { mood: "excited", message: "Boss battle time! You've got this!" }, layla: null },
    13: { adam: null, layla: { mood: "thumbsup", message: "You're now a Stranger Spotter! Amazing!" } },
  },
};
