import type { WeekContent } from "./types";

export const WEEK_4: WeekContent = {
  weekNumber: 4,
  title: "Scams & Tricks: Don't Get Fooled!",
  topic: "scams",
  badgeName: "Scam Detector",
  badgeIcon: "🕵️",

  introCutscene: [
    { text: "CYBER HEROES ACADEMY\nWEEK 4: SCAMS & TRICKS", bg: "normal", duration: 3000 },
    { character: "both", characterMood: "excited", text: "Back for Week 4, Cyber Hero? You're doing great!", sound: "lessonStart", duration: 5000 },
    { character: "raccoon", characterMood: "idle", text: "\"CONGRATULATIONS! You're our 1,000,000th visitor! Click here to claim your FREE iPhone!!!\"", bg: "danger", textColour: "#fca5a5", sound: "bossRoar", duration: 5500 },
    { character: "adam", characterMood: "worried", text: "The Hacker Raccoon is running FAKE prize scams! He's trying to trick kids into giving away passwords and info.", bg: "danger", duration: 5500 },
    { character: "layla", characterMood: "thinking", text: "A scam is a trick that makes you THINK you're getting something good, when really someone's trying to steal from you.", duration: 5500 },
    { character: "adam", characterMood: "thumbsup", text: "If it sounds TOO GOOD TO BE TRUE - it probably is! Free prizes, huge wins, mystery gifts... they're usually scams.", duration: 5500 },
    { character: "layla", characterMood: "excited", text: "Today we'll learn to spot ALL of Raccoon's sneaky scams. Let's become Scam Detectors!", sound: "select", duration: 5000 },
    { text: "MISSION START! 🕵️", bg: "normal", sound: "confetti", duration: 2000 },
  ],

  screens: [
    { type: "video", videoPlaceholder: "Week 4: Scams & Tricks intro video" },
    {
      type: "mission",
      objectives: [
        "Understand what scams are and why they work",
        "Spot the 5 common scam warning signs",
        "Know exactly what to do when you see a scam",
      ],
    },
    {
      type: "info",
      title: "What Is a Scam?",
      content:
        "A scam is a trick designed to steal your money, passwords, or personal info by pretending to offer something good. Scammers are like the Hacker Raccoon - they make things LOOK real, but they're fake.",
      bullets: [
        "Scams feel exciting - a prize, a reward, a freebie",
        "They rush you - 'act NOW or miss out!'",
        "They ask for info - your password, address, or parent's card",
        "They hide the truth - the 'prize' never actually exists",
      ],
    },
    {
      type: "cyberScanner",
      items: [
        { text: "'Congratulations! You won a free iPad!'", isStrong: false, explanation: "Random prize pop-ups are almost always scams" },
        { text: "An email from your real school account", isStrong: true, explanation: "Known sender, normal school stuff - safe" },
        { text: "'Your account will be DELETED in 1 hour - click now!'", isStrong: false, explanation: "Urgency is a scam classic - they want you to panic and click" },
        { text: "A text from Mum reminding you about dinner", isStrong: true, explanation: "From someone you know, normal content - safe" },
        { text: "'Click here for 10,000 FREE Robux!'", isStrong: false, explanation: "Free currency offers are the #1 scam targeting kids" },
        { text: "Your dad sharing a photo in the family chat", isStrong: true, explanation: "Trusted sender, expected content - safe" },
        { text: "'We noticed suspicious activity. Enter your password NOW.'", isStrong: false, explanation: "Real companies never ask for your password by email" },
        { text: "A calendar reminder for football practice", isStrong: true, explanation: "Your own reminder - totally safe" },
        { text: "'You've been chosen for a secret reward! Keep it hidden.'", isStrong: false, explanation: "Secrecy is a massive red flag in any scam" },
        { text: "A teacher's weekly homework message", isStrong: true, explanation: "Expected message from a known trusted sender" },
      ],
    },
    {
      type: "info",
      title: "The 5 Scam Warning Signs",
      content: "Every scam has at least ONE of these signs. Spot any of them and you know something's off.",
      bullets: [
        "Too good to be true - 'FREE' massive prizes out of nowhere",
        "Urgent pressure - 'Act NOW or lose it!' to stop you thinking",
        "Asks for secrets - passwords, card numbers, or home address",
        "Weird spelling or links - 'r0blox.xyz' instead of 'roblox.com'",
        "Asks you to keep it a secret from parents - ALWAYS a red flag",
      ],
    },
    {
      type: "spamBlaster",
      emails: [
        { sender: "FreeStuffDaily", subject: "🎉 YOU WON A PS5!!! Click to claim!", isPhishing: true, clue: "Random prize you never entered = scam" },
        { sender: "Mum", subject: "Can you pick up milk on the way home?", isPhishing: false, clue: "" },
        { sender: "Robux Team", subject: "FREE 10,000 Robux - enter password now!", isPhishing: true, clue: "Real Roblox NEVER asks for your password by email" },
        { sender: "Ms Thompson", subject: "Class photo next Thursday - smart uniform", isPhishing: false, clue: "" },
        { sender: "Security Alert", subject: "URGENT: Your account will be DELETED in 1 hour", isPhishing: true, clue: "Fake urgency + threats = classic scam" },
        { sender: "Best Friend Jenna", subject: "Did you see that funny tiktok I sent?", isPhishing: false, clue: "" },
        { sender: "App1e Supp0rt", subject: "Verify your Apple ID immediately", isPhishing: true, clue: "Notice the zeros - 'App1e' with a 1, not an L" },
        { sender: "School Office", subject: "Parents' evening rescheduled to Oct 12th", isPhishing: false, clue: "" },
        { sender: "Lucky Winner", subject: "Final chance - claim your £500 Amazon voucher!", isPhishing: true, clue: "'Final chance' + random prize = pressure scam" },
        { sender: "Uncle Dave", subject: "Happy birthday for tomorrow! 🎂", isPhishing: false, clue: "" },
      ],
    },
    {
      type: "chooseYourPath",
      scenarios: [
        {
          setup: "A pop-up says: 'CONGRATULATIONS! You're the 1,000,000th visitor! Click here to claim your FREE iPhone!!!' What do you do?",
          choices: [
            { text: "Click it - free iPhone!", isSafe: false, consequence: "Oh no! That was a scam. The website tried to steal your personal info - no iPhone exists." },
            { text: "Close the pop-up and tell a parent", isSafe: true, consequence: "Perfect! Random prize pop-ups are NEVER real. You dodged a scam." },
          ],
        },
        {
          setup: "Someone messages you on a game: 'I work for Roblox! If you give me your password, I'll add 50,000 Robux to your account!' What do you do?",
          choices: [
            { text: "Share your password - 50,000 Robux is amazing!", isSafe: false, consequence: "Disaster! They stole your account, your Robux, AND any payment info linked to it." },
            { text: "Report them and tell a parent", isSafe: true, consequence: "Real Roblox staff would NEVER ask for your password. You spotted the scam perfectly." },
          ],
        },
        {
          setup: "You get an email: 'Dear costumer, your acount is comprimised. Clik here to fix.' What do you notice?",
          choices: [
            { text: "Click the link - it says my account is in trouble!", isSafe: false, consequence: "The spelling mistakes were a clue! Real companies proofread their emails. You just clicked a dangerous link." },
            { text: "Spot the bad spelling and delete it", isSafe: true, consequence: "Excellent! Real companies never send emails this badly spelled. Classic scam signs." },
          ],
        },
        {
          setup: "A text says: 'HMRC: You're owed £250. Click here to claim within 24 hours.' What should you do?",
          choices: [
            { text: "Click - it might be real money owed to you!", isSafe: false, consequence: "HMRC doesn't text random links. This was a phishing scam and clicking it put your family at risk." },
            { text: "Delete it and show a parent", isSafe: true, consequence: "Smart! Government agencies never text surprise money offers. Always check with an adult." },
          ],
        },
      ],
    },
    {
      type: "memoryMatch",
      pairs: [
        { term: "Phishing", match: "Fake messages trying to steal info", colour: "#ef4444" },
        { term: "Scareware", match: "Fake 'YOUR COMPUTER HAS A VIRUS!' pop-ups", colour: "#f97316" },
        { term: "Fake Prize", match: "'You won!' when you never entered", colour: "#fbbf24" },
        { term: "Urgent Pressure", match: "'Act NOW or lose your account!'", colour: "#8b5cf6" },
        { term: "Red Flag URL", match: "r0blox.xyz instead of roblox.com", colour: "#60a5fa" },
        { term: "Safe Response", match: "Don't click. Show a parent.", colour: "#34d399" },
      ],
    },
    {
      type: "info",
      title: "STOP. THINK. CHECK.",
      content: "Before you click ANYTHING that feels exciting or urgent, follow these three steps:",
      bullets: [
        "STOP - don't click right away, even if it feels urgent",
        "THINK - does this sound too good to be true? Am I being rushed?",
        "CHECK - show a trusted adult BEFORE doing anything",
      ],
    },
    {
      type: "protectTheData",
      items: [
        { text: "Your password", isPrivate: true },
        { text: "Your favourite colour", isPrivate: false },
        { text: "Your parent's credit card number", isPrivate: true },
        { text: "Your favourite film", isPrivate: false },
        { text: "Your home address", isPrivate: true },
        { text: "Your favourite hobby", isPrivate: false },
        { text: "Your birthday (exact date)", isPrivate: true },
        { text: "Your pet's name", isPrivate: true },
        { text: "Your favourite pizza topping", isPrivate: false },
        { text: "Your bank account info", isPrivate: true },
        { text: "Your favourite sport", isPrivate: false },
        { text: "Your email password", isPrivate: true },
      ],
    },
    {
      type: "firewallBuilder",
      goodBlocks: [
        "Stop before clicking",
        "Ask a parent",
        "Check the URL carefully",
        "Delete suspicious emails",
        "Report scams to the platform",
        "Never share passwords",
        "Look for spelling mistakes",
        "Ignore urgency pressure",
      ],
      badBlocks: [
        "Click every flashy link",
        "Believe every 'You won!' message",
        "Enter passwords in pop-ups",
        "Ignore weird URLs",
      ],
    },
    {
      type: "cyberMaze",
      questions: [
        { question: "If something online sounds TOO GOOD TO BE TRUE it probably...", answers: ["Is a scam", "Just got lucky", "Is a gift", "Is a reward"], correctIndex: 0 },
        { question: "A message that says 'act NOW or lose everything!' is using...", answers: ["Fake urgency to pressure you", "Normal politeness", "Grammar", "A joke"], correctIndex: 0 },
        { question: "Real companies NEVER ask for your password by...", answers: ["Email or text message", "Their official login page", "Customer support phone lines", "Their mobile app"], correctIndex: 0 },
        { question: "One red flag in a URL is...", answers: ["Weird spelling like 'r0blox.xyz'", "The word 'home'", "A dot between words", "Lower-case letters"], correctIndex: 0 },
        { question: "The safest reaction to a suspicious message is...", answers: ["Stop, think, show a trusted adult", "Click it fast to not miss out", "Reply and ask them to prove it", "Share it with friends"], correctIndex: 0 },
      ],
    },
    { type: "bossBattle" },
    { type: "completion" },
  ],

  bossQuestions: {
    easy: [
      { question: "What is a scam?", answers: ["A trick to steal your info or money", "A type of computer game", "A fun email", "A school subject"], correctIndex: 0, explanation: "Scams are tricks designed to take something from you" },
      { question: "A pop-up says 'You won a free phone!' Should you click?", answers: ["Yes - free phone!", "No - random prizes are scams", "Maybe - only on Tuesdays", "Yes if it has emojis"], correctIndex: 1, explanation: "Random prize pop-ups are almost always scams" },
      { question: "'URGENT! Click NOW!' is using what trick?", answers: ["Kindness", "Fake urgency to make you panic-click", "Politeness", "A secret code"], correctIndex: 1, explanation: "Scammers rush you so you don't have time to think" },
      { question: "If an email has lots of spelling mistakes it's probably...", answers: ["A scam", "From a teacher", "Official", "Urgent"], correctIndex: 0, explanation: "Real companies check their spelling - bad spelling is a major scam sign" },
      { question: "Real Roblox staff ask for your password when?", answers: ["Every Monday", "Never", "Only for big prizes", "Only if you ask"], correctIndex: 1, explanation: "Real game companies NEVER ask for your password by chat or email" },
      { question: "If a stranger offers you 'free V-Bucks' for your info they are...", answers: ["Being very kind", "Running a scam", "A Fortnite employee", "Celebrating their birthday"], correctIndex: 1, explanation: "'Free' currency offers are the most common scam targeting kids" },
      { question: "Before clicking anything suspicious you should...", answers: ["Click it quickly", "Show a trusted adult first", "Forward it to friends", "Reply to the sender"], correctIndex: 1, explanation: "Always check with a parent or teacher before clicking anything unexpected" },
      { question: "Which URL looks fake?", answers: ["roblox.com", "r0blox-free.xyz", "bbc.co.uk", "google.com"], correctIndex: 1, explanation: "Zeros instead of letters and weird endings like .xyz are scam red flags" },
      { question: "A scam that asks for your password is called...", answers: ["Phishing", "Texting", "Cooking", "Typing"], correctIndex: 0, explanation: "Phishing is when scammers 'fish' for your passwords and info" },
      { question: "The Hacker Raccoon wants you to click quickly so you...", answers: ["Have fun", "Don't have time to think", "Can message him", "Learn faster"], correctIndex: 1, explanation: "Scammers rush you because they know you'd spot the scam if you thought about it" },
    ],
    medium: [
      { question: "'Scareware' is a scam that uses...", answers: ["Funny pictures", "Fake virus warnings to scare you into clicking", "Real viruses", "Free games"], correctIndex: 1, explanation: "Scareware pretends your device has a virus to make you panic-click a fake fix" },
      { question: "A text from 'HMRC' about a refund is almost always...", answers: ["Real - they owe you money", "A scam - HMRC doesn't text random links", "A test", "From your teacher"], correctIndex: 1, explanation: "Government agencies never text you surprise money through random links" },
      { question: "What does 'phishing' mean?", answers: ["Fishing with friends", "Using fake messages to 'fish' for your info", "A type of virus", "A game in Minecraft"], correctIndex: 1, explanation: "Phishing is the name for scam messages trying to hook your personal info" },
      { question: "A 'too good to be true' offer usually is...", answers: ["True", "Not true - it's a scam", "Illegal but real", "A surprise gift"], correctIndex: 1, explanation: "If something seems impossibly good, it's almost always a lie" },
      { question: "You get an email from 'App1e Support'. What's wrong?", answers: ["Nothing, that's normal", "The '1' is a fake letter in Apple - it's a scam", "Apple wrote it wrong", "The sender is typing fast"], correctIndex: 1, explanation: "Scammers use numbers that look like letters to trick you: 'App1e' not 'Apple'" },
      { question: "Why do scammers want you to keep things a secret from parents?", answers: ["Parents spoil surprises", "Because parents would spot the scam", "It's tradition", "Privacy reasons"], correctIndex: 1, explanation: "Scammers know adults are harder to trick, so they try to isolate kids" },
      { question: "A scam offering free stuff often really wants...", answers: ["Your passwords or info", "To be kind", "To give you presents", "To have fun"], correctIndex: 0, explanation: "The 'free' thing is just bait - what they really want is your information" },
      { question: "Which is the safest response to a suspicious pop-up?", answers: ["Click 'X' and close the tab, then tell an adult", "Click 'OK' to make it go away", "Click the big button in the middle", "Reply to it"], correctIndex: 0, explanation: "Always close suspicious pop-ups with the X and tell a trusted adult" },
      { question: "A game chat message says 'I'm a mod, give me your password to verify.' What's happening?", answers: ["They're a real moderator being helpful", "It's a scam - mods never need your password", "They're doing a prize draw", "It's a test from the game"], correctIndex: 1, explanation: "Real moderators have their own tools - they NEVER need your password" },
      { question: "If you clicked a scam link by accident you should...", answers: ["Keep it secret", "Tell a trusted adult immediately so they can help", "Delete the whole internet", "Ignore it"], correctIndex: 1, explanation: "Mistakes happen - telling an adult quickly helps fix things fast" },
    ],
    hard: [
      { question: "'Vishing' is phishing that uses what?", answers: ["Videos only", "Voice calls - fake phone calls", "Vikings", "Vowels"], correctIndex: 1, explanation: "Vishing = voice + phishing, when scammers phone pretending to be banks or support" },
      { question: "'Smishing' is a scam that uses...", answers: ["Smell", "SMS (text messages)", "Smudging", "Smiles"], correctIndex: 1, explanation: "Smishing = SMS + phishing, scam text messages with fake links" },
      { question: "A scammer pretending to be from your school district asks for your full name and class. What should you do?", answers: ["Reply - they already know your school", "Never share info unless a parent confirms they're real", "Give only your first name", "Ask them to prove it online"], correctIndex: 1, explanation: "Scammers research public info to sound real. Always verify through a parent, not through the scammer" },
      { question: "Why do scammers often target kids specifically?", answers: ["Kids have the best computers", "Kids may have less experience spotting tricks and fewer checks on their devices", "It's a game", "It's random"], correctIndex: 1, explanation: "Scammers know kids are learning online safety - that's why we teach it early" },
      { question: "A 'romance scam' targets people by...", answers: ["Giving roses", "Pretending to fall in love to steal money or info", "Celebrating Valentine's Day", "Playing romantic songs"], correctIndex: 1, explanation: "Romance scams are about fake feelings - another reason never to trust strangers online" },
      { question: "If a scam email has YOUR name and school in it why shouldn't you trust it?", answers: ["Your info can be found publicly - that doesn't make a sender real", "It's always real if they know you", "Scammers can't guess names", "Schools leak everything"], correctIndex: 0, explanation: "Just because a message knows things about you doesn't mean the sender is genuine - that info is often public" },
      { question: "A scammer uses 'social engineering' which means...", answers: ["Building actual social networks", "Manipulating people using psychology instead of hacking computers", "Fixing roads", "Teaching social studies"], correctIndex: 1, explanation: "Social engineering is hacking people's minds - trust, fear, urgency - rather than hacking computers" },
      { question: "You see a 'charity fundraiser' email asking for a bank transfer. How do you verify it?", answers: ["Ignore the email and search for the real charity directly", "Send a small amount first as a test", "Forward it to friends", "Reply asking for proof"], correctIndex: 0, explanation: "Don't use links IN the email. Go to the real charity's website separately and check" },
      { question: "A scam message uses 'deepfake' audio of a family member asking for help. The clue it's fake is...", answers: ["Even the voice can be faked - always verify by calling them back on a known number", "Family members never ask for help", "Deepfakes aren't real yet", "Audio can't be faked"], correctIndex: 0, explanation: "Modern scams can fake voices. If someone 'family' asks for urgent help, call them back on a number you already know" },
      { question: "The best long-term defence against scams is...", answers: ["Having the newest phone", "Staying curious and suspicious - especially when rushed or excited", "Blocking everyone", "Never going online"], correctIndex: 1, explanation: "Scams evolve but the tactics - rush, fake excitement, asking for info - stay the same. Stay alert" },
    ],
  },

  reactions: {
    0: { adam: { mood: "excited", message: "Welcome to Scam School, Cyber Hero!" }, layla: null },
    1: { adam: null, layla: { mood: "curious", message: "Today we learn how scams trick people." } },
    2: { adam: { mood: "thinking", message: "Scams are tricks - they LOOK real but they're fake." }, layla: null },
    3: { adam: null, layla: { mood: "excited", message: "Scan each message - is it safe or a scam?" } },
    4: { adam: { mood: "worried", message: "Five warning signs every scam uses. Memorise them!" }, layla: null },
    5: { adam: null, layla: { mood: "thumbsup", message: "Zap every phishing email!" } },
    6: { adam: { mood: "thinking", message: "Real decisions - which door is the safe one?" }, layla: null },
    7: { adam: null, layla: { mood: "curious", message: "Match up the scam terms!" } },
    8: { adam: { mood: "thumbsup", message: "Stop. Think. Check. Three steps to beat any scam." }, layla: null },
    9: { adam: null, layla: { mood: "excited", message: "Protect the private stuff - scammers want it!" } },
    10: { adam: { mood: "excited", message: "Build the scam-blocking firewall!" }, layla: null },
    11: { adam: null, layla: { mood: "thinking", message: "Answer each gate to escape the scam maze." } },
    12: { adam: { mood: "excited", message: "Boss battle - the Raccoon's ultimate scam!" }, layla: null },
    13: { adam: null, layla: { mood: "thumbsup", message: "Scam Detector unlocked. Nothing gets past you!" } },
  },
};
